### ISSUE TITLE
sfdx force:source:retrieve unexpected error troubleshooting

### ISSUE THREAD

**Issue by peternoges** [forcedotcom/cli#375] opened 2020-04-17 18:29 UTC
Hello.  Using an updated CLI and v48 package.xml I'm noticing failures during a retrieve operation: ERROR running force:source:retrieve:  The metadata retrieve operation failed: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1429875284-1147988 (-1001565770)

I've narrowed it down and found that when I remove several wildcarded types from the package it retrieves successfully.  Here are the wildcard types that I removed from package.xml to get the retrieve to succeed.   I believe at least one of these is to blame.  The CLI is not telling me which is to blame.   Have these each been tested in isolation and are there any known bugs with wildcard retrieving any of these named types?

	<types>
		<members>*</members>
		<name>ActionLinkGroupTemplate</name>
	</types>
		<types>
		<members>*</members>
		<name>AnimationRule</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexClass</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexComponent</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexPage</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexTestSuite</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexTrigger</name>
	</types>
	<types>
		<members>*</members>
		<name>AppMenu</name>
	</types>
	<types>
		<members>*</members>
		<name>ApprovalProcess</name>
	</types>
	<types>
		<members>*</members>
		<name>AssignmentRules</name>
	</types>
	<types>
		<members>*</members>
		<name>AuraDefinitionBundle</name>
	</types>
	<types>
		<members>*</members>
		<name>AuthProvider</name>
	</types>
	<types>
		<members>*</members>
		<name>AutoResponseRules</name>
	</types>
	<types>
		<members>*</members>
		<name>BrandingSet</name>
	</types>
	<types>
		<members>*</members>
		<name>CallCenter</name>
	</types>
	<types>
		<members>*</members>
		<name>CampaignInfluenceModel</name>
	</types>
	<types>
		<members>*</members>
		<name>Certificate</name>
	</types>
	<types>
		<members>*</members>
		<name>ChannelLayout</name>
	</types>
	<types>
		<members>*</members>
		<name>ChatterExtension</name>
	</types>
	<types>
		<members>*</members>
		<name>CleanDataService</name>
	</types>
	<types>
		<members>*</members>
		<name>Community</name>
	</types>
	<types>
		<members>*</members>
		<name>ConnectedApp</name>
	</types>
	<types>
		<members>*</members>
		<name>ContentAsset</name>
	</types>
	<types>
		<members>*</members>
		<name>CorsWhitelistOrigin</name>
	</types>
	<types>
		<members>*</members>
		<name>CspTrustedSite</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomApplication</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomApplicationComponent</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomFeedFilter</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomHelpMenuSection</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomLabels</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomMetadata</name>
	</types>
		<types>
		<members>*</members>
		<name>CustomObjectTranslation</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomPageWebLink</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomPermission</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomSite</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomTab</name>
	</types>
	<types>
		<members>*</members>
		<name>DataCategoryGroup</name>
	</types>
	<types>
		<members>*</members>
		<name>DelegateGroup</name>
	</types>
	<types>
		<members>*</members>
		<name>DuplicateRule</name>
	</types>
	<types>
		<members>*</members>
		<name>EclairGeoData</name>
	</types>
		<types>
		<members>*</members>
		<name>ExternalDataSource</name>
	</types>
	<types>
		<members>*</members>
		<name>ExternalServiceRegistration</name>
	</types>
	<types>
		<members>*</members>
		<name>FlexiPage</name>
	</types>
	<types>
		<members>*</members>
		<name>Flow</name>
	</types>
	<types>
		<members>*</members>
		<name>FlowCategory</name>
	</types>
	<types>
		<members>*</members>
		<name>FlowDefinition</name>
	</types>
	<types>
		<members>*</members>
		<name>GlobalValueSet</name>
	</types>
	<types>
		<members>*</members>
		<name>GlobalValueSetTranslation</name>
	</types>
	<types>
		<members>*</members>
		<name>Group</name>
	</types>
	<types>
		<members>*</members>
		<name>HomePageComponent</name>
	</types>
	<types>
		<members>*</members>
		<name>HomePageLayout</name>
	</types>
	<types>
		<members>*</members>
		<name>InstalledPackage</name>
	</types>
	<types>
		<members>*</members>
		<name>Layout</name>
	</types>
		<types>
		<members>*</members>
		<name>LightningBolt</name>
	</types>
	<types>
		<members>*</members>
		<name>LightningComponentBundle</name>
	</types>
	<types>
		<members>*</members>
		<name>LightningExperienceTheme</name>
	</types>
	<types>
		<members>*</members>
		<name>LightningMessageChannel</name>
	</types>
	<types>
		<members>*</members>
		<name>MatchingRules</name>
	</types>
	<types>
		<members>*</members>
		<name>MyDomainDiscoverableLogin</name>
	</types>
	<types>
		<members>*</members>
		<name>NamedCredential</name>
	</types>
	<types>
		<members>*</members>
		<name>NetworkBranding</name>
	</types>
		<types>
		<members>*</members>
		<name>OauthCustomScope</name>
	</types>
	<types>
		<members>*</members>
		<name>PathAssistant</name>
	</types>
	<types>
		<members>*</members>
		<name>PermissionSet</name>
	</types>
	<types>
		<members>*</members>
		<name>PlatformCachePartition</name>
	</types>
	<types>
		<members>*</members>
		<name>PlatformEventChannel</name>
	</types>
	<types>
		<members>*</members>
		<name>PlatformEventChannelMember</name>
	</types>
	<types>
		<members>*</members>
		<name>PostTemplate</name>
	</types>
	<types>
		<members>*</members>
		<name>Profile</name>
	</types>
	<types>
		<members>*</members>
		<name>ProfilePasswordPolicy</name>
	</types>
	<types>
		<members>*</members>
		<name>ProfileSessionSetting</name>
	</types>
	<types>
		<members>*</members>
		<name>Prompt</name>
	</types>
	<types>
		<members>*</members>
		<name>Queue</name>
	</types>
	<types>
		<members>*</members>
		<name>QuickAction</name>
	</types>
	<types>
		<members>*</members>
		<name>RecommendationStrategy</name>
	</types>
	<types>
		<members>*</members>
		<name>RecordActionDeployment</name>
	</types>
	<types>
		<members>*</members>
		<name>RedirectWhitelistUrl</name>
	</types>
	<types>
		<members>*</members>
		<name>ReportType</name>
	</types>
	<types>
		<members>*</members>
		<name>Role</name>
	</types>
	<types>
		<members>*</members>
		<name>SamlSsoConfig</name>
	</types>
	<types>
		<members>*</members>
		<name>Scontrol</name>
	</types>
	<types>
		<members>*</members>
		<name>Settings</name>
	</types>
	<types>
		<members>*</members>
		<name>SharingRules</name>
	</types>
	<types>
		<members>*</members>
		<name>SiteDotCom</name>
	</types>
	<types>
		<members>*</members>
		<name>StandardValueSetTranslation</name>
	</types>
	<types>
		<members>*</members>
		<name>StaticResource</name>
	</types>
	<types>
		<members>*</members>
		<name>SynonymDictionary</name>
	</types>
	<types>
		<members>*</members>
		<name>TopicsForObjects</name>
	</types>
	<types>
		<members>*</members>
		<name>Workflow</name>
	</types>

**Comment by clairebianchi** [comment] 2020-04-28 18:28
@peternoges did you contact support? They would need your org ID and the Gack ID and they would be able to identify the metadata type that is causing the issue.

**Comment by RupertBarrow** [comment] 2020-04-30 23:40
Duplicate of #151

**Closed as completed** 2020-05-05 18:50 UTC
Labels: more information required
