### ISSUE TITLE
Source deploy fails when switching to a branch where a field + translation is removed/does not exist

### ISSUE THREAD

**Issue by guillaumezeeman** [forcedotcom/cli#2281] opened 2023-07-04 09:56 UTC
### Summary
When we switch from a branch with an field and field translations to a branch that does not have that field, we get an exception when trying to push our changes to an scratch org. 
`Error (1): Unexpected child metadata [sfdx-source/sobjects/objectTranslations/User-en_US/testField__c.fieldTranslation-meta.xml] found for parent type [CustomObjectTranslation]`

This prevents us from updating our orgs and can only be resolved if we switch from a branch which does not have said field, resetting the source tracking and updating the org from there by switching to the branch we want to push to our org.

**Context**
This scenario often happens when we switch from branches for certain features. Let's say we're working on an issue based on the master branch. For this issue we create a new field for the 'User' object that includes field translations. We push these changes to our scratch org and later commit them to our feature branch. Everything still works fine.

We're now ready to develop another feature and therefor create a new feature branch based on the master. We then try to update out scratch org with said feature branch and we get the aforementioned exception.

### Steps To Reproduce
It is fairly easy to reproduce this issue.

1. Create a scratch org with the source code of the master branch
2. Create a new feature branch based on the master
3. Create a field for the 'User' object, let's say 'customField__c' with multiple translation files (en_US, fr, de and nl_NL)
4. Push this new field to your scratch org (source tracking must be updated) with the 'sfdx project deploy start' command
5. Commit and push this new field to your feature branch
6. Create a new feature branch based on the master branch
7. Switch to this new branch
8. Update your scratch org with this new feature branch with the 'sfdx project deploy start' command

I do not have a repo that I can share, as the problem occurs with an application of a private company and the source code is not open source.

### Expected result
Your scratch org is updated with the new feature branch (in essence the master branch)

### Actual result
You get an exception:
`Error (1): Unexpected child metadata [sfdx-source/sobjects/objectTranslations/User-en_US/testField__c.fieldTranslation-meta.xml] found for parent type [CustomObjectTranslation]`

### System Information
**System:** MacOS Ventura 13.0.1 (22A400)
**Terminal:** zsh
**SFDX version:**
```json
{
  "cliVersion": "sfdx-cli/7.207.3",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v20.2.0",
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/usr/local/lib/node_modules/sfdx-cli",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 19.4.1 (link) /Users/guillaumezeeman/Documents/Repositories/other/sfpowerscripts/packages/sfpowerscripts-cli",
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.16 (core)",
    "@oclif/plugin-help 5.2.10 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.3 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.19 (core)",
    "@oclif/plugin-version 1.3.5 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.39 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "apex 2.3.3 (core)",
    "auth 2.8.2 (core)",
    "community 2.3.2 (core)",
    "custom-metadata 2.1.26 (core)",
    "data 2.3.26 (core)",
    "deploy-retrieve 1.13.1 (core)",
    "info 2.6.22 (core)",
    "limits 2.3.22 (core)",
    "org 2.9.14 (core)",
    "packaging 1.20.0 (core)",
    "schema 2.3.14 (core)",
    "settings 1.4.14 (core)",
    "signups 1.4.22 (core)",
    "source 2.10.15 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.4.22 (core)",
    "trust 2.4.22 (core)",
    "user 2.3.17 (core)",
    "ntvdx 1.0.0 (link) /Users/guillaumezeeman/Documents/Repositories/other/ntvdx-plugin",
    "sfdmu 4.17.6 (user)",
    "sfdx-browserforce-plugin 2.11.0 (user)",
    "sfdx-cli 7.207.3 (core)",
    "sfpowerkit 5.0.0 (link) /Users/guillaumezeeman/Documents/Repositories/other/sfpowerkit"
  ]
}
```

This issue also occurs in the current latest version of SFDX (7.208.10), which I currently do not have installed due to a bug in that version that occurs for me.

### Additional information
**None**

**Comment by guillaumezeeman** [comment] 2023-07-04 09:59
I have updated to the suggested SFDX version and tried the scenario again but that unfortunately does not resolve my issue.

**Comment by guillaumezeeman** [comment] 2023-07-04 11:09
I have updated to the suggested SFDX version and tried the scenario again but that unfortunately does not resolve my issue. 
```json
{
  "cliVersion": "sfdx-cli/7.207.5",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v20.2.0",
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/usr/local/lib/node_modules/sfdx-cli",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 19.4.1 (link) /Users/guillaumezeeman/Documents/Repositories/other/sfpowerscripts/packages/sfpowerscripts-cli",
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.16 (core)",
    "@oclif/plugin-help 5.2.10 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.3 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.19 (core)",
    "@oclif/plugin-version 1.3.5 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.39 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "apex 2.3.3 (core)",
    "auth 2.8.2 (core)",
    "community 2.3.2 (core)",
    "custom-metadata 2.1.26 (core)",
    "data 2.3.26 (core)",
    "deploy-retrieve 1.13.3 (core)",
    "info 2.6.22 (core)",
    "limits 2.3.22 (core)",
    "org 2.9.14 (core)",
    "packaging 1.20.0 (core)",
    "schema 2.3.14 (core)",
    "settings 1.4.14 (core)",
    "signups 1.4.22 (core)",
    "source 2.10.19 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.4.22 (core)",
    "trust 2.4.22 (core)",
    "user 2.3.17 (core)",
    "ntvdx 1.0.0 (link) /Users/guillaumezeeman/Documents/Repositories/other/ntvdx-plugin",
    "sfdmu 4.17.6 (user)",
    "sfdx-browserforce-plugin 2.11.0 (user)",
    "sfdx-cli 7.207.5 (core)",
    "sfpowerkit 5.0.0 (link) /Users/guillaumezeeman/Documents/Repositories/other/sfpowerkit"
  ]
}
```

**Comment by HippieHosenHustler** [comment] 2023-07-27 17:43
Hi 👋 

I just wanted to chime in and say that we are facing the same issue. @guillaumezeeman have you found a workaround perhaps? 

Right now it looks like we need to just not deploy field translation and instead update that information manually in the target org, which is suboptimal as it undermines the concept of having git as the single source of truth. We are also on the latest version of sfdx.

**Comment by guillaumezeeman** [comment] 2023-07-29 10:44
Yes, maybe...sort of. You must switch to a branch where the field and field translation is not included in and do a source tracking reset `sfdx project reset tracking -p` before switching to your new branch. So in the case I describes in the issue, you would reset the source tracking when switching back to the master branch and before checking out your new feature branch. This of course does not remove the new logic from the first feature branch, but at least you can continue with your scratch org.

But the use case we presented is simply to reproduce the issue. The use case we actually have is when we would remove a certain field and all new feature branches would have the same issues. For example, we removed a certain custom field (including the translation files) from the user entity, let's say 'customField__c' and were to merge this in a release branch. Everyone that would update their feature branch with the latest changes in the release branch would get this issue. The only solution we have discovered is to also delete the 'customField__c' field in your feature branch before hand, do a source tracking reset and then update your feature branch with the release branch. This way, SFDX source tracking will not try to delete the custom field and therefor not throw this error.

**Comment by cristiand391** [comment] 2024-02-16 19:23
Closing this as it's working as designed.

Users should use 1 scratch org per feature work, trying to re-use it for multiple work like describe here will trigger this sort of metadata (`Error (1): Unexpected child metadata` is a valid error, it needs the parent metadata to be able to convert it to the mdapi format needed for a deploy/retrieve).

See: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs.htm

**Closed as not planned by cristiand391** 2024-02-16 19:23 UTC
Labels: investigating, validated
