### ISSUE TITLE
Unable to create scratch org - Error code : C-1034

### ISSUE THREAD

**Issue by pietroz123** [forcedotcom/cli#1930] opened 2023-02-12 00:40 UTC
### Summary

I am unable to create a scratch org with the `sfdx force:org:create` command.

### Steps To Reproduce:

Use the command:
`sfdx force:org:create -s -f ./config/project-scratch-def.json -a MC94 --durationdays 30`

### Expected result

Expected the scratch org to be created.

### Actual result

Got an error:
`The request to create a scratch org failed with error code: C-1034.`

### System Information

Mac OS: Ventura 13.0.1
SFDX: sfdx-cli/7.187.1
Node.js: v18.13.0

### Additional information

project-scratch-def.json

```json
{
  "orgName": "Dev.",
  "edition": "Developer",
  "hasSampleData": false,
  "language": "en_US",
  "features": ["EinsteinAnalyticsPlus"],
  "settings": {
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "userManagementSettings": {
      "enableNewProfileUI": true
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    }
  }
}
```

sfdx-project.json

```json
...
    "sourceApiVersion": "55.0",
...
```

**Comment by idanblich** [comment] 2023-02-12 08:42
looks like related to this [Known Issue - spring-23-north-american-sandbox-feature-disruption](https://trailblazer.salesforce.com/issues_view?id=a1p4V000003BIYGQA4&title=spring-23-north-american-sandbox-feature-disruption)

**Comment by ferhatco** [comment] 2023-02-13 11:11
I am also facing same issue. Even if I use the new commands it is giving me same error. 

`sfdx org create scratch -y 30 --definition-file config/project-scratch-def.json --alias sfo1 --target-dev-hub myDevHub`

The output is 
`Warning: This command is currently in beta. Any aspect of this command can change without advanced notice. Don't use beta commands in your scripts.

Error (1): The request to create a scratch org failed with error code: C-1033.`

**Comment by ferhatco** [comment] 2023-02-13 11:27
I fixed my issue, the issue is because of the Spring 23 release. You need to define "release": "preview" in your scratch org definition file.

**Comment by mshanemc** [comment] 2023-02-13 13:57
duplicate of #1931

**Closed as completed by mshanemc** 2023-02-13 13:57 UTC
Labels: investigating
