### ISSUE TITLE
unsupported metadata type ManagedContentType

### ISSUE THREAD

**Issue by vsbharath** [forcedotcom/cli#408] opened 2020-05-16 03:06 UTC
ERROR running force:source:retrieve:  We can’t retrieve the specified metadata object: ManagedContentType. Certain metadata types, like ManagedContentType are not currently supported by the CLI.

unsupported metadata type ManagedContentType

**Comment by AltiusRupert** [comment] 2020-05-16 11:22
Duplicate of #151

**Closed as completed** 2020-05-21 19:02 UTC
Labels: duplicate
