### ISSUE TITLE
force:source:deploy Failing

### ISSUE THREAD

**Issue by nikhil-sfdev** [forcedotcom/cli#888] opened 2021-02-26 12:35 UTC
While deploying from cli, receiving JSON_PARSER_ERROR. 

### Steps To Reproduce:

`sfdx force:source:deploy -p "./PathToMetadata" -l RunSpecifiedTests -r TestClass1,TestClass2 -w 33 --verbose --loglevel fatal
`
### Actual result
Using specified username admin@adminx.com

*** Deploying with REST ***
_ERROR running force:source:deploy:  JSON_PARSER_ERROR: Can not deserialize: unexpected array at [line:1, column:73]_

### Additional information

macOS 11.2.1 sfdx-cli/7.89.2-d1d2614d02 darwin-x64 node-v14.15.4

**Comment by dweaver33** [comment] 2021-02-26 13:42
Related to #884

**Comment by shetzel** [comment] 2021-03-02 22:10
Duplicate of #884 and #860.  See details on those issues for workarounds.

**Closed as completed by shetzel** 2021-03-02 22:10 UTC
Labels: investigating

**Comment by dgonch5** [comment] 2021-03-09 18:40
Same issue with sfdx-cli/7.85.1-2fb9e41053 win32-x64 node-v12.18.3
