### ISSUE TITLE
Error force:source:deploy EMFILE: too many open files

### ISSUE THREAD

**Issue by JuliWaver** [forcedotcom/cli#487] opened 2020-07-15 15:02 UTC
### Summary

sfdx deploy command is not working anymore and following error is shown:
ERROR running force:source:deploy:  EMFILE: too many open files, open "dir to any random file"

Used command: sfdx force:source:deploy --verbose --targetusername "Sandbox Alias" -p force-app -c

Several reboots were done and no files are open. Shown file dir in error message is random and is changing everytime.

### Steps To Reproduce:

**Repository to reproduce:** Not reproducable with [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc).

### Expected result

Validation is starting without any error messages shown.

### Actual result

Error message is shown and no validation or deployment is possible.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.65.4-c99e705754 win32-x64 node-v12.13.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)+
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 48.22.8 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ salesforce-alm 48.24.1 (core)
└─ custom-metadata 1.0.4 (core)
sfdx-cli 7.65.4 (core)

**OS and version**: Windows 10, Version10.0.17763 Build 17763

**Comment by kidjansen** [comment] 2020-07-17 12:05
Also applicable with retrieve: https://github.com/forcedotcom/cli/issues/494

**Comment by clairebianchi** [comment] 2020-07-21 18:17
Duplicate of https://github.com/forcedotcom/cli/issues/494

**Closed as completed by clairebianchi** 2020-07-21 18:17 UTC
Labels: bug, duplicate
