### ISSUE TITLE
SFDX Plugin Install can't find the Package in the Private NPM (We are using Nexus)

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#411] opened 2020-05-18 18:14 UTC
When running sfdx plugins:install hpe-sfdx-plugins, I receive the following message

![image](https://user-images.githubusercontent.com/55927613/82245811-8ca58780-993b-11ea-94c8-f06289314fe7.png)

If I use the public NPM registry everything works fine. Due to compliance issues I had to migrate my package to a private registry and now I can't install the plugin.
The only thing I changed in the Plugin's package.json was this

![image](https://user-images.githubusercontent.com/55927613/82245946-c4acca80-993b-11ea-9432-be1eb26b3538.png)

Im also able to install the package using ````npm install hpe-sfdx-plugins```` without a problem.
In the image below I show my global registry (the private one), and after that I install with success the hpe-sfdx-plugins package and then I try to install using ````sfdx plugins:install hpe-sfdx-plugins```` and it does not work.
![image](https://user-images.githubusercontent.com/55927613/82251489-363d4680-9945-11ea-8114-80384f9fcd8a.png)

**Comment by AllanOricil** [comment] 2020-05-18 22:49
I opened another one for the sfdx-core repo https://github.com/forcedotcom/sfdx-core/issues/233
In this one I described where is the problem and how I fixed.

**Comment by mdonnalley** [comment] 2020-05-21 19:08
Duplicate of https://github.com/forcedotcom/cli/issues/410

**Closed as completed by mdonnalley** 2020-05-21 19:08 UTC
Labels: duplicate
