### ISSUE TITLE
ERROR running force:source:convert:  The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by RedaBenh** [forcedotcom/cli#219] opened 2019-04-04 13:18 UTC
### Summary

unable to convert sfdx project to mdapi project. no details about the error.

### Steps To Reproduce:

1.  Clone my project from git
1.  Run the command `sfdx force:source:convert -r force-app/main/default/ -d src`

### Expected result
Convert successfully with the message:
Source was successfully converted to Metadata API format and written to the location: ~/src

### Actual result
Getting this error without details:
```
$ sfdx force:source:convert -r force-app/main/default/ -d src
ERROR running force:source:convert:  The "path" argument must be of type string. Received type object
```

### Additional information

big project with large metadata components

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.1.4 linux-x64 node-v10.15.3`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
```
 ›   Warning: You acknowledge and agree that the CLI tool may collect usage information, user environment, and crash reports for
 ›   the purposes of providing services or functions that are relevant to use of the CLI tool and product improvements.
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.8.2 (core)
├─ force-language-services 45.9.0 (core)
└─ salesforce-alm 45.11.0 (core)

sfdx-cli 7.1.4 (core)
```
**OS and version**:
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by clairebianchi** [comment] 2019-11-01 17:37
This looks to be related to https://github.com/forcedotcom/cli/issues/94 I am moving to the CLI issues repo and will add this information to the internal bug we have for this issue

**Comment by mshanemc** [comment] 2021-05-20 14:26
closing, duplicate of #94

**Closed as completed by mshanemc** 2021-05-20 14:26 UTC
Labels: bug
