### ISSUE TITLE
 sfdx force:source:convert undefined path issue

### ISSUE THREAD

**Issue by every26** [forcedotcom/cli#495] opened 2020-07-16 16:56 UTC
I have been using the convert functionality for quite some time... here is the command i run....

 sfdx force:source:convert -r C:\Users\HB35401\MAXDev\force-app\main\default\_FilesToConvert -d C:\Users\HB35401\Downloads\Conversions -n 'package'

when i run the command i get the below error... 
![image](https://user-images.githubusercontent.com/33691364/87699955-9bee5900-c763-11ea-92fd-dea92000eb34.png)

my sfdx-project.json file looks like this...
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "48.0"
}

**Comment by alizar-balink** [comment] 2020-07-17 05:45
See issue https://github.com/forcedotcom/cli/issues/493
You have to run the command now from the folder containing the sfdx-project.json.  That is the workaround.

**Comment by shetzel** [comment] 2020-07-21 18:53
Duplicate of #488

**Closed as completed by shetzel** 2020-07-21 18:53 UTC
