### ISSUE TITLE
sfdx force:source:deploy is not deploying the custom fields.

### ISSUE THREAD

**Issue by ar-srinivas** [forcedotcom/cli#628] opened 2020-09-21 11:53 UTC
### Summary

sfdx force:source:deploy is not deploying the custom fields and skipping custom fields when bundled with any other metadata.

### Steps To Reproduce:

**Repository to reproduce:** [https://github.com/ar-srinivas/SFDX_CustomFields.git](https://github.com/ar-srinivas/SFDX_CustomFields.git)
Branch: **Dev**

1.  Clone the "Dev" branch source
1.  Run the following command from source folder. sfdx force:source:deploy -x package.xml -u <targetorg> --apiversion=49.0 -w 0 --json

### Expected result

The two custom fields from the source structure should be deployed to the target org. CLI should return deployment ID and status. The behavior should remain same when we pass -x package.xml or -m "CustomField"

### Actual result

Result is shown as below

{
  "status": 0,
  "result": {
    "outboundFiles": [],
    "deploys": []
  }
}

### Additional information

It is failing to deploy custom fields when I add -x package.xml but when I replace it with -m "CustomField" the deployment is processed succesfuly.
![image](https://user-images.githubusercontent.com/30531295/93762955-2654ac80-fc2e-11ea-9121-9a590ec47e77.png)

Also skipping the custom fields when included any other metadata.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.74.1-32db2396ed win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**: Windows 10

**Comment by shetzel** [comment] 2020-09-23 16:41
This is actively being worked on and the fix will be included in the next patch release.

**Comment by nabondance** [comment] 2020-09-28 09:07
Until the patch is released (Oct. 1st), a working workaround is to change the salesforcedx version using:
`sfdx plugins:install salesforcedx@49.9.2`

Special thanks to @alanjaouen

**Comment by engineerakki** [comment] 2020-10-07 03:53
Is this fixed ?
I dont want to change salesforcedx version.
I am still getting the same issue

**Comment by vnehess** [comment] 2020-10-07 21:30
I have encountered this in my development as well, the problem: not creating custom fields, seems to follow the latest cli version - 7.75.0
earlier versions always created the fields, I was using 7.63.0.

**Comment by FinnArild** [comment] 2020-10-14 07:30
I can also confirm this issue in versions 7.75.0 and 7.75.1

**Comment by akashpunera** [comment] 2020-10-16 11:57
This issue is still not resolved, facing this in 7.75.0 as well

**Comment by 1ktribble** [comment] 2020-10-16 21:00
7.75.1 - when deploying a new custom field alongside a new dependent picklist, the dependent picklist fails to deploy. 

Error: `In field: controllingField - no CustomField named field_name__c found`

Both fields are in the <CustomField> object in the package.xml file. This occurs with both the source:deploy and mdapi:deploy commands.

**Closed as completed** 2020-10-18 03:45 UTC
Labels: bug

**Comment by girasedinesh** [comment] 2020-10-20 15:22
I am also facing the same issue from last two weeks. I have 8 new custom fields from one object, added them in package.xml, but it deployed only first field from the list. Even i tried adding CustomObject section in the package.xml, but result is still same. **This is happening on production instance, its working fine on sandboxes though.**

**Comment by shetzel** [comment] 2020-10-20 15:38
@girasedinesh 
If the output of `sfdx plugins --core` doesn't match this then you probably don't have the fix.  The code works the same regardless of production versus sandbox versus scratch org.
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
config 1.1.9 (core)
generator 1.1.3 (core)
salesforcedx 50.1.1 (core)
├─ apex 0.1.1 (core)
├─ custom-metadata 1.0.10 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 50.1.1 (core)
sfdx-cli 7.76.1 (core)

If your plugins match this then provide steps to reproduce since it's working properly for me and others.

**Comment by girasedinesh** [comment] 2020-10-20 15:58
This is what i am getting
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
config 1.1.9 (core)
generator 1.1.3 (core)
salesforcedx 50.1.1 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
├─ salesforce-alm 50.1.1 (core)
└─ apex 0.1.1 (core)
sfdx-cli 7.76.1 (core)

**Comment by girasedinesh** [comment] 2020-10-20 16:51
I am using similar package.xml in the manifest folder for deployment
"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>SomeCustomObject__c.Field1__c</members>
		<members>SomeCustomObject__c.Field2__c</members>
		<members>SomeCustomObject__c.Field3__c</members>
		<members>SomeCustomObject__c.Field4__c</members>
		<members>SomeCustomObject__c.Field5__c</members>
		<name>CustomField</name>
	</types>
	<version>49.0</version>
</Package>"

**Comment by girasedinesh** [comment] 2020-10-20 16:54
![image](https://user-images.githubusercontent.com/59448789/96618787-63669a00-12d3-11eb-837c-7b9cd425836f.png)

**Comment by shetzel** [comment] 2020-10-20 19:01
@girasedinesh - I would try uninstalling the CLI and reinstalling to the latest.

**Comment by girasedinesh** [comment] 2020-10-20 19:13
Its resolved now. Docker image from our yml file was not picking the latest version, now it started picking the latest version. Thanks all for your valuable suggestions.

**Comment by shetzel** [comment] 2020-10-20 19:23
@girasedinesh - Glad you got it working!  👍

**Comment by ravishankar-peri** [comment] 2020-11-05 10:54
I see the same problem with Workflow* types.

**Comment by jitendrabhagatdevops** [comment] 2020-12-04 17:55
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
config 1.1.9 (core)
generator 1.1.3 (core)
salesforcedx 50.1.1 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.10 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 50.1.1 (core)
sfdx-cli 7.82.1-0 (core)


I have this , still I am not able to deploy the custom field,  is this bug RESOLVED in this version of SFDX - sfdx-cli 7.82.1-0

**Comment by shetzel** [comment] 2020-12-07 16:59
@jitendrabhagatdevops - I don't know how you have `salesforcedx 50.1.1 (core)` with `sfdx-cli 7.82.1 (core)` but that is the problem.  You should be on version 50.7.1 of the salesforcedx plugin.  Please run `sfdx update`
