### ISSUE TITLE
ERROR running force:source:convert:  Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by alizar-balink** [forcedotcom/cli#493] opened 2020-07-16 05:48 UTC
### Summary

I need to convert metadata from the file format with -meta.xml to .layout or other similar types.  This worked for me last week, but now I get the error: 
ERROR running force:source:convert:  Cannot read property 'path' of undefined

### Steps To Reproduce:

I am running the command:
sfdx force:source:convert --rootdir layouts --outputdir tmp

### Expected result

expected is successful convert of the layout metadata files into a folder layouts under tmp folder.

### Actual result

The error "ERROR running force:source:convert:  Cannot read property 'path' of undefined"

### Additional information

Afterwards the retrieve command also gives the same error.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.65.4-c99e705754 win32-x64 node-v12.13.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 48.22.8 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 48.24.1 (core)
└─ custom-metadata 1.0.4 (core)
sfdx-cli 7.65.4 (core)

**OS and version**:
Windows 10

**Comment by every26** [comment] 2020-07-16 17:26
Im getting the same issue. Please reply if you have a fix. thanks!

**Comment by JonnyPower** [comment] 2020-07-16 17:26
Likely same underlying reason as https://github.com/forcedotcom/cli/issues/488

**Comment by alizar-balink** [comment] 2020-07-16 18:44
Yes.  I was able to avoid the problem by running the command from the root
folder.
*Aliza Reishtein*
Team Leader | Balink LTD

site: balink.net
Salesforce Platinum Partner

**Comment by shetzel** [comment] 2020-07-21 18:54
Duplicate of #488

**Closed as completed by shetzel** 2020-07-21 18:54 UTC

**Comment by jcatterson** [comment] 2022-04-21 19:50
I've seen this issue if the sfdx repository is missing paths in sfdx-project.json
Make sure those paths exist referenced there
