### ISSUE TITLE
sfdx force:source:deploy --sourcepath not uploading files to org (since 10/03/2021).

### ISSUE THREAD

**Issue by luisjamora** [forcedotcom/cli#913] opened 2021-03-11 17:13 UTC
### Summary

sfdx force:source:deploy --sourcepath not uploading file to org (since 10/03/2021).
1 each 10 times class is deployed.

### Steps To Reproduce:

Modify class in vscode
Excecute command sfdx force:source:deploy

### Expected result

Class deployed to ORG
### Actual result

No error shown, no class deployed:
12:16:38.514 sfdx force:source:deploy --sourcepath XXX.cls --json --loglevel fatal
 ended with exit code 0

### Additional information

**SFDX CLI Version**: sfdx-cli/7.90.2-b8f9206a5c win32-x64 node-v14.15.4

**SFDX plugin Version**: 
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-2 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.4.10 (core)
config 1.2.6 (core)
generator 1.1.5 (core)
salesforcedx 51.1.1 (core)
├─ limits 1.0.4 (core)
├─ schema 1.0.4 (core)
├─ user 1.1.2 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ templates 51.3.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.1.1 (core)
sfdx-cli 7.90.2 (core)
telemetry 1.1.1 (core)

**OS and version**: Windows 10 Pro

**VSCODE:
Version: 1.54.1 (system setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Salesforce extension pack version: 51.4.0

**Comment by vikyaiyer** [comment] 2021-03-16 06:55
#904 already raise for this

**Comment by shetzel** [comment] 2021-03-16 22:54
duplicate of #904

**Closed as completed by shetzel** 2021-03-16 22:54 UTC
Labels: investigating
