### ISSUE TITLE
ERROR running force:mdapi:deploy: INVALID_OPERATION: No zip file content passed in

### ISSUE THREAD

**Issue by amtrack** [forcedotcom/cli#284] opened 2020-01-27 10:36 UTC
### Summary

We've spotted an intermittent error:

> ERROR running force:mdapi:deploy: INVALID_OPERATION: No zip file content passed in

Apparently this is not a new error: https://developer.salesforce.com/forums/?id=9062I000000IDc2QAG

See below for my investigation of creating the zip file in `salesforce-alm`.

### Steps To Reproduce:

I cannot reproduce this intermittent error.

This is what we are doing when the error occurs:

```console
$ sfdx force:mdapi:deploy -d mdapi/remove-sample-metadata -w 15 -u my-scratch-org --apiversion=47.0
```

These are the files in the given folder, however I doubt these files are of any interest.

**mdapi/remove-sample-metadata/package.xml**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>44.0</version>
</Package>
```

**mdapi/remove-sample-metadata/destructiveChanges.xml**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Case.Standard</members>
        <members>Lead.Standard</members>
        <name>AssignmentRule</name>
    </types>
    <types>
        <members>Account.Active__c</members>
        <members>Account.CustomerPriority__c</members>
        <members>Account.NumberofLocations__c</members>
        <members>Account.SLAExpirationDate__c</members>
        <members>Account.SLASerialNumber__c</members>
        <members>Account.SLA__c</members>
        <members>Account.UpsellOpportunity__c</members>
        <members>Contact.Languages__c</members>
        <members>Contact.Level__c</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>Case.Standard</members>
        <name>EscalationRule</name>
    </types>
</Package>
```

### Expected result

It should have created and uploaded the zip file.

### Actual result

It failed creating/uploading the zip file.

### Additional information

Looking at the source code of `salesforce-alm`, it appears that `mdapi` and `source` commands are slightly different in creating the zip file using the `node-archiver` package.
While mdapi commands resolve the zip file receiving the `end` event of node-archiver, source commands resolve on the `close` event.
Is there a reason for this?

**node_modules/salesforce-alm/dist/lib/mdapi/mdapiDeployApi.js**

```javascript
            archive.on('end', () => {
                this.logger.debug(`${archive.pointer()} bytes written to ${outFile} using ${this._getElapsedTime()}ms`);
                resolve(outFile);
            });
```

**node_modules/salesforce-alm/dist/lib/core/srcDevUtil.js**

```javascript
            output.on('close', () => {
                resolve(outFile);
            });
```

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.43.1 linux-x64 node-v11.10.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.4.1 (core)
generator 1.1.2 (core)
salesforcedx 47.16.0 (core)
├─ salesforcedx-templates 47.17.0 (core)
└─ salesforce-alm 47.15.0 (core)

**OS and version**: Ubuntu 16.04.6 LTS (Travis CI)

**Comment by clairebianchi** [comment] 2020-01-31 21:50
@amtrack I will pass this on the team that owns the metadata api and see if they can get to the bottom of it.

**Comment by felixpelletier** [comment] 2020-07-03 19:27
Any update on this issue?

**Comment by mshanemc** [comment] 2023-06-22 16:02
I'm going to close this issue--pretty much ALL of the code handling deploys has been replaced since then (SDR library, new commands, etc).  

If you've got a recent reproduction, please open a new issue.

**Closed as completed by mshanemc** 2023-06-22 16:02 UTC
Labels: owned by another team
