### ISSUE TITLE
We can’t retrieve the specified metadata object: Audience. Certain metadata types, like Audience are not currently supported by the CLI.

### ISSUE THREAD

**Issue by Sandhirasegaran** [forcedotcom/cli#573] opened 2020-08-21 09:46 UTC
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**:

**Comment by shetzel** [comment] 2020-09-10 16:38
duplicate of #571

**Closed as completed by shetzel** 2020-09-10 16:38 UTC
Labels: duplicate
