### ISSUE TITLE
An error occurred while trying to install a package dependency - Custom Metadata Issue with 1Gp Dependency

### ISSUE THREAD

**Issue by Starz26** [forcedotcom/cli#1584] opened 2022-06-23 15:49 UTC
### Summary

sfdx-cli/7.155.1 darwin-x64 node-v16.15.1

When attempting to create a 2GP package that has a dependency on a 1GP managed package. 

### Steps To Reproduce:

 sfdx force:package:version:create --installationkeybypass -p 0Ho5Y000000PAvlSAG -c -w 30

### Expected result

Package Created

### Actual result

SFDX Error

An error occurred while trying to install a package dependency, ID 04t3g000000TqTY: (Security_Key.AES_Key) Data Not Available, Details: The data you were trying to access could not be found. It may be due to another user deleting the data or a system error. If you know the data is not deleted but cannot access it, please look at our <A href="{0}" title="support{1}">support</a> page.

This started yesterday as far as I can tell.

Security_Key is a MDT Object
AES_Key is a Custom Metadata Record

The 1GP dependency in this 2GP package version that I am trying to create has been there for 6 previous versions of the 2GP package and the 04t version has not changed. Just now it is throwing this error

As an aside, the 1GP 04t package installs fine into the 2GP scratch org.

**Comment by shetzel** [comment] 2022-06-23 19:56
duplicate of #1582

**Closed as completed by shetzel** 2022-06-23 19:56 UTC
Labels: investigating
