### ISSUE TITLE
XML file is not downloaded when LWC is retrieved

### ISSUE THREAD

**Issue by Emmandez** [forcedotcom/cli#717] opened 2020-10-30 17:03 UTC
### Summary

There are some Lightning Web Components in a sandbox that were developed by other coworkers and I would like to download them. 
When I retrieve them using SFDX, the folder only contains CSS, HTML, and JS files, so It's not possible to deploy it back due to the lack of the XML file.
![image](https://user-images.githubusercontent.com/17038938/97733256-3a959000-1a9d-11eb-892b-e485a985d0cb.png)

I've noticed that if the LWC has a CSS file, SFDX will only download the CSS, HTML, and JS files, with no XML file.
![image](https://user-images.githubusercontent.com/17038938/97733831-f5259280-1a9d-11eb-8174-3dd4666fdf7e.png)

But if the LWC does not have a CSS file, the retrieved files are HTML, JS and XML files
![image](https://user-images.githubusercontent.com/17038938/97734145-62d1be80-1a9e-11eb-91bc-a019c2a7ed0d.png)

### Steps To Reproduce:

1.  Using VSCode, download a Lightning Web Component developed by another person that has a CSS file from the Org.

### Expected result

The folder should contain CSS, HTML, JS and JS-XML files

### Actual result

The folder does not contain the XML file.

### Additional information

**SFDX CLI Version** sfdx-cli/7.78.1-5a65d9dd2f win32-x64 node-v12.18.3

**SFDX plugin Version** 
![image](https://user-images.githubusercontent.com/17038938/97734448-cfe55400-1a9e-11eb-9fdd-9f5d381fe23e.png)

**OS and version**: Windows 10 Pro version 1909

**Comment by Iamsfdeveloper** [comment] 2020-11-16 19:17
An object 'componentName' of type LightningComponentBundle was named in package.xml, but was not found in zipped directory
sfdx-cli/7.80.0-b979aae708 darwin-x64 node-v12.18.3

**Comment by shetzel** [comment] 2020-11-16 23:16
duplicate of #563 
The fix for this will be in the release this Thursday.  salesforcedx v50.6.0, sfdx-cli v7.81.0.  You can try it early using the release candidate.  `sfdx plugins:install salesforcedx@latest-rc`

**Closed as completed by shetzel** 2020-11-16 23:16 UTC
