### ISSUE TITLE
Org alias only assigned to one scratch org when multiple scratch orgs are created in parallel

### ISSUE THREAD

**Issue by johnzhao9** [forcedotcom/cli#1806] opened 2022-11-14 22:43 UTC
### Summary

When creating multiple scratch orgs in parallel via `force:org:create --setalias`, the `--setalias` only applies alias to a single org

### Steps To Reproduce:

**Repository to reproduce:** [sfdx-rep2](https://github.com/johnzhao9/sfdx-rep2) 

1.  Clone the repository
1.  Connect to a devhub org
2.  Do `bash run`, or execute what's in the `run` file

### Expected result
expecting `sfdx force:org:list` to give
```
   ALIAS            USERNAME
   CM              test-0cfq96xpoere@example.com 00D0t000000UkHuEAK 2022-11-15
   ACM-Antunit      test-poj0c5y2prrf@example.com 00D2D000000H951UAC 2022-11-15
```
with alias assigned to both orgs (CM to 0cfq..., ACM-Antunit to poj0...)

### Actual result
```
   ALIAS            USERNAME
                    test-0cfq96xpoere@example.com 00D0t000000UkHuEAK 2022-11-15
   ACM-Antunit      test-poj0c5y2prrf@example.com 00D2D000000H951UAC 2022-11-15
```
The first org doesn't have an alias.
### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
A: Bash

 `sfdx version --verbose --json`
```
{
  "cliVersion": "sfdx-cli/7.176.1",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.12.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.5 (core)",
    "@oclif/plugin-commands 2.2.1 (core)",
    "@oclif/plugin-help 5.1.17 (core)",
    "@oclif/plugin-not-found 2.3.7 (core)",
    "@oclif/plugin-plugins 2.1.6 (core)",
    "@oclif/plugin-update 3.0.6 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.12 (core)",
    "@oclif/plugin-which 2.1.1 (core)",
    "alias 2.1.7 (core)",
    "apex 1.3.0 (core)",
    "auth 2.2.19 (core)",
    "community 2.0.14 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.3 (core)",
    "data 2.1.7 (core)",
    "generator 2.0.9 (core)",
    "info 2.2.4 (core)",
    "limits 2.0.10 (core)",
    "org 2.2.11 (core)",
    "packaging 1.10.1 (core)",
    "schema 2.1.12 (core)",
    "signups 1.2.11 (core)",
    "source 2.3.0 (core)",
    "telemetry 2.0.2 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.4 (core)",
    "user 2.1.16 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.3 (core)"
  ],
  "osVersion": "Linux 5.15.0-1020-aws",
  "shell": "bash",
  "rootPath": "/root/.local/share/sfdx/client/7.176.1-458b658"
}
```
### Additional information
System 
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
- When creating four orgs in parallel, I end up with 3 orgs without alias and only 1 with alias.
- The same issue happens when using Apache Ant's `parallel` task to run `org:create` in parallel
- The last version we were using was really old: `7.72.0-697e9faee2`, so I'm not sure if this has been working recently, but it didn't have this issue in that really old version.
- The issue appears in version 7.175.0 as well. Later updated with `sfdx update` to 7.176.1 as shown above and still occuring

**Comment by daveespo** [comment] 2022-11-15 00:57
Aliases are an alternative way to refer to scratch org instead of using the username. It seems like it's 'working as designed' to ensure that two SOs don't share the same alias .. otherwise the behavior of using the alias in other command would be undefined.

**Comment by johnzhao9** [comment] 2022-11-15 02:26
> Aliases are an alternative way to refer to scratch org instead of using the username. It seems like it's 'working as designed' to ensure that two SOs don't share the same alias .. otherwise the behavior of using the alias in other command would be undefined.

Thanks for the fast response, The alias aren't the same, to make the example clearer I've updated the example repo to use these two aliases:
CM
ACM-Antunit

I've tested and the same issue happens with those two.

**Comment by mshanemc** [comment] 2022-11-15 13:41
I marked this as a bug.  We're aware that the the [configFile](https://github.com/forcedotcom/sfdx-core/tree/main/src/config) family of classes, which includes Aliases, isn't friendly to parallelism (processes can cross-save each other).  

The fix is not simple, so I'd recommend not trying to assign aliases in parallel (for example, you could create org in parallel since that takes a while, but then use `alias:set` after the fact since each of those would be pretty fast).

**Comment by johnzhao9** [comment] 2022-11-15 14:28
> I marked this as a bug. We're aware that the the [configFile](https://github.com/forcedotcom/sfdx-core/tree/main/src/config) family of classes, which includes Aliases, isn't friendly to parallelism (processes can cross-save each other).
> 
> The fix is not simple, so I'd recommend not trying to assign aliases in parallel (for example, you could create org in parallel since that takes a while, but then use `alias:set` after the fact since each of those would be pretty fast).
 
Makes sense, I will try setting the aliases separately and make sure they run sequentially. I'll also look at those classes and see what other commands I need to be careful with. Appreciate the background info and the help on this!

**Closed as completed** 2023-06-22 12:23 UTC
Labels: bug, configFile
