### ISSUE TITLE
Can not Retrieve MutingPermissionSet with Sfxd

### ISSUE THREAD

**Issue by Ezegerez** [forcedotcom/cli#751] opened 2020-11-27 12:34 UTC
**Summary**

I am trying to retrieve the MutingPermissionSet to my branch and it gives me an error. I also followed the example of the package found in this link **https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_mutingpermissionset.htm**  and i get an error too.

### Steps To Reproduce:

1.  In VSCode, go to Org Browser, found MuttingPermissionSet and try to retrieve it.

### Expected result

Retrieve the MutingPermissionSet to my branch.

### Actual result

_09:25:03.883 sfdx force:source:retrieve --json --loglevel fatal -m MutingPermissionSet:Asistente_Comercial_PSG_Muted_Opportunity
{
  "status": 1,
  "name": "UnsupportedType",
  "message": "The specified metadata type is unsupported: [MutingPermissionSet]",
  "exitCode": 1,
  "commandName": "SourceRetrieveCommand",

### Additional information

![image](https://user-images.githubusercontent.com/64573638/100449992-9e5aab00-3093-11eb-8987-b7cfe75085a8.png)

**SFDX Version**
sfdx-cli/7.81.0-7b953c80d1 win32-x64 node-v12.18.3

**SFDX plugin Version**
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.6.0 (core)
├─ schema 1.0.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 50.6.0 (core)
├─ templates 50.1.0 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.81.0 (core)
sfpowerkit 2.3.6 (beta)

**Comment by shetzel** [comment] 2020-12-28 17:43
Duplicate of #339 
Support will be enabled in the first patch release of 2021.

**Closed as completed by shetzel** 2020-12-28 17:43 UTC
Labels: duplicate
