### ISSUE TITLE
Command source:push progress bar causes excessive console output in CI/CD jobs

### ISSUE THREAD

**Issue by peternhale** [forcedotcom/cli#324] opened 2020-02-28 16:43 UTC
### Summary

Command source:push progress bar causes excessive console output in CI/CD jobs

### Steps To Reproduce:

1.  Create a Jenkins job that includes a force:source:push command
1.  Run `sfdx force:source:push` without using `--json` flag
1. Run the job

### Observed results

The Jenkins log will receive one line of output for each update of the progress bar

```
[2020-02-24T20:00:11.156Z] + ./dx-cli/sfdx force:source:push
[2020-02-24T20:00:26.027Z] Job ID | 0Af11000012iSDNCA2
[2020-02-24T20:00:26.027Z] SOURCE PROGRESS | ████████████████████████████████████████ | 0/0 Files
[2020-02-24T20:00:26.027Z] SOURCE PROGRESS | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0/855 Files
[2020-02-24T20:00:26.027Z] SOURCE PROGRESS | ███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 63/855 Files
[2020-02-24T20:00:26.963Z] SOURCE PROGRESS | ███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 74/855 Files
[2020-02-24T20:00:27.896Z] SOURCE PROGRESS | ███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 74/855 Files
[2020-02-24T20:00:28.830Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 75/855 Files
[2020-02-24T20:00:29.398Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
[2020-02-24T20:00:30.333Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
[2020-02-24T20:00:30.901Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
[2020-02-24T20:00:31.851Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
[2020-02-24T20:00:32.423Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
[2020-02-24T20:00:33.358Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
[2020-02-24T20:00:33.924Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
[2020-02-24T20:00:34.860Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
[2020-02-24T20:00:35.427Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
[2020-02-24T20:00:36.362Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
[2020-02-24T20:00:36.929Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
[2020-02-24T20:00:37.864Z] SOURCE PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 76/855 Files
...
[2020-02-24T20:04:52.653Z] SOURCE PROGRESS | ████████████████████████████████████████ | 855/855 Files
```

### Run ob with env var SFDX_USE_PROGRESS_BAR=false to disable progress bar

1. In Jenkins job config set env var SFDX_USE_PROGRESS_BAR=false
1. Create a Jenkins job that includes a force:source:push command
1.  Run `sfdx force:source:push` without using `--json` flag
1. Run the job

### Observed results

The Jenkins log will receive many lines of output for each update of progress
```
[2020-02-27T17:31:01.750Z] ./dx-cli/sfdx force:source:push
[2020-02-27T17:31:01.757Z] [Pipeline] sh
[2020-02-27T17:31:02.044Z] + ./dx-cli/sfdx force:source:push
[2020-02-27T17:31:14.249Z] Job ID | 0Af2100000ZdMF3CAN
[2020-02-27T17:31:14.249Z] 
[2020-02-27T17:31:14.249Z] Status:  Pending
[2020-02-27T17:31:14.249Z] jobid:  0Af2100000ZdMF3CAN
[2020-02-27T17:31:14.250Z] Component errors:  0
[2020-02-27T17:31:14.250Z] Components deployed:  0
[2020-02-27T17:31:14.250Z] Components total:  0
[2020-02-27T17:31:14.250Z] Tests errors:  0
[2020-02-27T17:31:14.250Z] Tests completed:  0
[2020-02-27T17:31:14.250Z] Tests total:  0
[2020-02-27T17:31:14.250Z] Check only: false
[2020-02-27T17:31:14.250Z] 
[2020-02-27T17:31:14.250Z] Status:  InProgress
[2020-02-27T17:31:14.250Z] jobid:  0Af2100000ZdMF3CAN
[2020-02-27T17:31:14.250Z] Component errors:  0
[2020-02-27T17:31:14.250Z] Components deployed:  0
[2020-02-27T17:31:14.250Z] Components total:  0
[2020-02-27T17:31:14.250Z] Tests errors:  0
[2020-02-27T17:31:14.250Z] Tests completed:  0
[2020-02-27T17:31:14.250Z] Tests total:  0
[2020-02-27T17:31:14.250Z] Check only: false
[2020-02-27T17:31:14.510Z] 
[2020-02-27T17:31:14.510Z] Status:  InProgress
[2020-02-27T17:31:14.510Z] jobid:  0Af2100000ZdMF3CAN
[2020-02-27T17:31:14.510Z] Component errors:  0
[2020-02-27T17:31:14.510Z] Components deployed:  0
[2020-02-27T17:31:14.510Z] Components total:  855
[2020-02-27T17:31:14.510Z] Tests errors:  0
[2020-02-27T17:31:14.510Z] Tests completed:  0
[2020-02-27T17:31:14.510Z] Tests total:  0
[2020-02-27T17:31:14.510Z] Check only: false
...
[2020-02-27T17:35:45.271Z] Status:  Succeeded
[2020-02-27T17:35:45.271Z] jobid:  0Af2100000ZdMF3CAN
[2020-02-27T17:35:45.271Z] Completed:  2020-02-27T17:35:44.000Z
[2020-02-27T17:35:45.271Z] Component errors:  0
[2020-02-27T17:35:45.271Z] Components deployed:  855
[2020-02-27T17:35:45.271Z] Components total:  855
[2020-02-27T17:35:45.271Z] Tests errors:  0
[2020-02-27T17:35:45.271Z] Tests completed:  0
[2020-02-27T17:35:45.271Z] Tests total:  0
[2020-02-27T17:35:45.271Z] Check only: false
[2020-02-27T17:35:45.271Z] === Pushed Source
```
### Additional information

Prior to the progress bar, the command emitted no updates until the push was complete. While getting updates via the progress bar is acceptable for use as a developer, the updates in a CI/CD environment are not helpful.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.48.0-a71f8c6899 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
sfdx plugins --core                
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/analytics 0.15.1
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
evergreen 0.13.1
└─ evergreen-build 0.4.2

generator 1.1.2 (core)
salesforcedx 48.3.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.4.0 (core)
└─ salesforce-alm 48.4.0 (core)

sfdx-cli 7.48.0 (core)
sfdx-dev 2.18.1
```

**Comment by vazexqi** [comment] 2020-02-28 16:48
Possible dupe of #289?

**Comment by vazexqi** [comment] 2020-02-28 16:49
🤔I wonder if we should just do `--json` and pipe it to /dev/null in our CI jobs for now.

**Comment by zerkz** [comment] 2020-02-28 17:06
it's a bit unclear as to what you desire to happen -- 

the release notes for the disabling of the progress bar do not state that they stop console output entirely -- https://developer.salesforce.com/media/salesforce-cli/releasenotes-v47.html 

A solution i can offer you in the mean time is to do an ASYNC deploy -- which you can check by executing another command with your own logic -- 

![image](https://user-images.githubusercontent.com/1448099/75569075-0ce1de00-5a1a-11ea-9302-7dab35b5866f.png)

note -- I don't work in scratch orgs sadly (our org isn't ready for them 100% yet), so i couldn't test the `push` version, but im hoping it works the same.

**Comment by amphro** [comment] 2020-02-28 18:45
I don't consider this a bug. What are the expected results you want? 

I think having progress in CI/CD runs **IS** helpful, even though it is a little excessive. That way if you are looking at the Jenkins output page, you can see something happening. There are a couple of things we could do to make it less excessive.

* We could not update the progress bar when there is the same amount of components. That would remove multiple progress bar lines with the same bar making the output a little more manageable. 
* For non-progress bar, we could have one line per status unless a `--verbose` is provided.

If you don't want any information outputted, then using `--json` or ignoring stdout is the right solution.

**Comment by clairebianchi** [comment] 2020-02-28 21:51
We published a blog on using CLI output a few weeks back https://developer.salesforce.com/blogs/2020/02/using-salesforce-cli-output-and-scripting.html

Please take a look at our guidelines

**Closed as completed by clairebianchi** 2020-02-28 21:51 UTC
