### ISSUE TITLE
Unable to create package version (Patch) 7.187.1-09910f2 - Error code : C-1034

### ISSUE THREAD

**Issue by idanblich** [forcedotcom/cli#1929] opened 2023-02-11 23:12 UTC
### Summary

Unable to create package version

### Steps To Reproduce:

Using a valid 2GP project 

```sfdx package:version:create --package Viewer2 --installation-key-bypass --wait 30 --code-coverage --target-hub-org PBO```
also 
``` sfdx package version create --package Viewer2 --installation-key-bypass --wait 30 --code-coverage --target-hub-org PBO```
also 
``` sfdx force:package:beta:version:create --package Viewer2 --installationkeybypass --wait 30  --codecoverage --target-hub-org PBO```
also 
``` sfdx force:package:legacy:version:create --package Viewer2 --installationkeybypass --wait 30  --codecoverage ```

### Expected result

Create Package Ver (Patch) 

### Actual result

start with:
 ```
Version create.... ⣻ 30 minutes remaining until timeout. Create version status: Initializing
``` 
but end after few seconds end with:
```
Version create.... Create version status: Error
Error (1): Multiple errors occurred: 
(1) An unexpected error occurred while preparing endpoint: C-1034.  Please contact Salesforce Support and provide the following error code: 1320833778-4800 (-1215335089)
```
### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
MacOS 13.1 +  zsh
- sfdx : 
{
  "cliVersion": "sfdx-cli/7.187.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.13.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.4.4 (core)",
    "@oclif/plugin-commands 2.2.5 (core)",
    "@oclif/plugin-help 5.2.2 (core)",
    "@oclif/plugin-not-found 2.3.17 (core)",
    "@oclif/plugin-plugins 2.3.0 (core)",
    "@oclif/plugin-search 0.0.11 (core)",
    "@oclif/plugin-update 3.1.1 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.24 (core)",
    "@oclif/plugin-which 2.2.12 (core)",
    "alias 2.2.0 (core)",
    "apex 1.5.0 (core)",
    "auth 2.4.0 (core)",
    "community 2.2.0 (core)",
    "config 1.5.0 (core)",
    "custom-metadata 2.1.0 (core)",
    "data 2.2.0 (core)",
    "generator 2.0.17 (core)",
    "info 2.4.0 (core)",
    "limits 2.3.0 (core)",
    "org 2.3.0 (core)",
    "packaging 1.14.1 (core)",
    "schema 2.3.0 (core)",
    "signups 1.4.0 (core)",
    "source 2.4.1 (core)",
    "telemetry 2.1.0 (core)",
    "templates 55.3.0 (core)",
    "trust 2.4.0 (core)",
    "user 2.3.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.5 (core)",
    "sfdmu 4.26.5 (user)"
  ],
  "osVersion": "Darwin 22.2.0",
  "shell": "zsh",
  "rootPath": "/Users/idan/.local/share/sfdx/client/7.187.1-09910f2"
}

**Comment by idanblich** [comment] 2023-02-12 08:41
looks like related to this [Known Issue - spring-23-north-american-sandbox-feature-disruption](https://trailblazer.salesforce.com/issues_view?id=a1p4V000003BIYGQA4&title=spring-23-north-american-sandbox-feature-disruption)


![image](https://user-images.githubusercontent.com/1132993/218301151-ed458346-56cf-4e7e-bb9e-78b0a1590018.png)

**Comment by aozomaro** [comment] 2023-02-12 14:43
+1 .. and sfdc case support are the most useless people at Salesforce. I’ve got to play back n forth comms for 24 hours and then they usually do not ack the issue. Thanks for finding the known issue, I was going mad.

**Comment by mshanemc** [comment] 2023-02-13 13:58
duplicate of #1931

**Closed as completed by mshanemc** 2023-02-13 13:58 UTC
Labels: investigating
