### ISSUE TITLE
Warnings of Resources Not Found in Local Project During Deployment Report

### ISSUE THREAD

**Issue by Alfystar** [forcedotcom/cli#2862] opened 2024-05-09 12:42 UTC
### Issue Description
After updating to version 2.40.7 of the Salesforce CLI, we started receiving warnings in our pipeline log. These warnings indicate that there are custom fields and Apex classes present in the Salesforce org but not found in the local project, despite the deployment operation completing successfully.

```
09-May-2024 11:49:29   >$ sf project deploy report --target-org <orgName> --job-id <JobId> --json
09-May-2024 11:49:29	Report warnings:
09-May-2024 11:49:29	 | CustomField, ITA_IFM_BasketItem__c.ITA_IFM_Partner__c, returned from org, but not found in the local project
09-May-2024 11:49:29	 | CustomField, ITA_IFM_BasketItem__c.ITA_IFM_BasketId__c, returned from org, but not found in the local project
09-May-2024 11:49:29	 | CustomField, ITA_IFM_BasketItem__c.ITA_IFM_RuleName__c, returned from org, but not found in the local project
09-May-2024 11:49:29	 | CustomField, Lead.ITA_IFM_Interest__c, returned from org, but not found in the local project
09-May-2024 11:49:29	 | CustomField, wrts_prcgvr__Activity__c.ITA_IFM_OwnerRiclassificazione__c, returned from org, but not found in the local project
....
[Last 2 lines containing the 2 resources contained in the destructiveChangesPost.xml]
09-May-2024 11:49:29	 | ApexClass, ITA_IFM_StartDisdettaStandardProces_Test, returned from org, but not found in the local project
09-May-2024 11:49:29	 | ApexClass, ITA_IFM_StartDisdettaStandardProcess, returned from org, but not found in the local project
```
### Steps to Reproduce
0. Start a dry-run deploy with sf-cli 
1. Run the command `sf project deploy report --target-org <orgName> --job-id <jobID> --json`.
2. Observe the warnings in the pipeline log.

### Expected Result
There should be no warnings about resources not found in the local project if they have been correctly handled in the package.xml and in the repository.

### Actual Result
We receive warnings for resources not found in the local project, even though the deployment operations have been executed successfully and the resources are present in the package.xml and in the repository.

### System Information

- Salesforce CLI Version: 2.40.7
- Workflow Type: Git-based
- Pipeline was running on Bash, with an agent based on Ubuntu 2023.
```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.40.7",
  "nodeVersion": "node-v20.12.2",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/ea_enel/.local/share/sf/client/2.40.7-bde121f",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.16 (core)",
    "@oclif/plugin-commands 3.3.1 (core)",
    "@oclif/plugin-help 6.0.21 (core)",
    "@oclif/plugin-not-found 3.1.7 (core)",
    "@oclif/plugin-plugins 5.0.18 (core)",
    "@oclif/plugin-search 1.0.23 (core)",
    "@oclif/plugin-update 4.2.9 (core)",
    "@oclif/plugin-version 2.0.17 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.16 (core)",
    "@oclif/plugin-which 3.1.8 (core)",
    "@salesforce/cli 2.40.7 (core)",
    "apex 3.1.11 (core)",
    "auth 3.6.5 (core)",
    "data 3.3.2 (core)",
    "deploy-retrieve 3.6.8 (core)",
    "info 3.2.4 (core)",
    "limits 3.3.4 (core)",
    "marketplace 1.2.4 (core)",
    "org 4.1.5 (core)",
    "packaging 2.4.1 (core)",
    "schema 3.3.4 (core)",
    "settings 2.2.3 (core)",
    "sobject 1.3.6 (core)",
    "source 3.3.5 (core)",
    "telemetry 3.3.4 (core)",
    "templates 56.2.4 (core)",
    "trust 3.6.7 (core)",
    "user 3.5.4 (core)",
    "sfdx-plugin-source-read 1.2.0 (user)"
  ]
}
```

**Comment by mdonnalley** [comment] 2024-05-09 16:35
@Alfystar Take a look at the [2.38.7 release notes](https://github.com/forcedotcom/cli/tree/main/releasenotes#2387-april-24-2024). Those warnings were added to solve an issue with `project deploy report` not showing all the results returned from the server.

**Comment by Alfystar** [comment] 2024-05-09 17:37
Thank you, I understand now, but I think this output is not correct, all the deployed resources were present on the project on which the report was run, more over, the deleted resources are correctly missing in project

**Comment by Alfystar** [comment] 2024-05-09 19:07
I don't think it's the correct result because the report is called on the same machine that performed the deployment, just 1 cmd before

Furthermore, the logs generated with version 2.38.7, which as you rightly pointed out solved the problem, did not show these warnings, in the same configuration and on the same machine

Same situation for logs generated with 2.39.6

The first time they appeared was today with version 2.40.7

The code automatically updates to the latest stable version of sf-cli

**Comment by mdonnalley** [comment] 2024-05-09 19:38
@Alfystar Are you able to provide a repository that replicates the issue you're seeing? The steps you provided don't replicate the issue using [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc)

**Comment by Alfystar** [comment] 2024-05-10 05:11
I try to recreate the problem and then share the repository with you. 

However, I realized that I didn't specify that our workflow is to generate a package in metadata format, from the source of the repository using sf-cli and then deploy that package, it's an important detail I think.


We inherited this flow from the structure we had with ANT, and too much was developed on that basis to abandon it completely, moreover reading the documentation I seemed to understand that internally sf-cli still creates a package in metadata format

**Comment by Alfystar** [comment] 2024-05-10 08:28
I recreated a scratch org as described in your readme in the repository:
https://github.com/trailheadapps/dreamhouse-lwc

I used the tools we developed to exactly recreate the problem with a deploy/delete validator of the apex classes.

I used our company tools to create the packages, but as you can easily see, the program logs clearly show which sf-cli commands are executed.

The part with the unexpected warnings is at the end of the log.

I hope that this evidence is sufficient and allows you to understand and solve this little problem introduced in this release.

```
10:13:43 ~/Documents/01_repo/dreamhouse-lwc  (main)
└─▶ $ metaOp.py local org mkOrg --alias dreamhouse                    
Namespace(typeOp='local', locOp='org', orgOp='mkOrg', base_org='/Users/ea_enel/Documents/01_repo/dreamhouse-lwc/Orgs', alias=['dreamhouse'], force=False, no_login=False)

>> Executing local-org-mkOrg operation:
[dreamhouse] >> Initializing Orgs/dreamhouse ...
[dreamhouse] 
[dreamhouse] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[dreamhouse] >> Searching org with Alias:= 'dreamhouse' in local DB...
[dreamhouse]  >$ sf org list auth --json
[dreamhouse] 
[dreamhouse] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[dreamhouse] >> Initializing authfile.json...
[dreamhouse]  >$ sf org display --target-org dreamhouse --verbose --json
[dreamhouse] Data extraction of dreamhouse Org complete.
[dreamhouse]  - Log inside Org: https://computing-saas-6400-dev-ed.scratch.my.salesforce.com
[dreamhouse]  - Using user:     test-aspfrg6dtixf@example.com
[dreamhouse]  - Api version:    60.0
[dreamhouse]  - Org alias:      dreamhouse
[dreamhouse] Warnings inside '/Users/ea_enel/Documents/01_repo/dreamhouse-lwc/Orgs/dreamhouse/authfile.json':
[dreamhouse]  | This command will expose sensitive information that allows for subsequent activity using your current authenticated session.
[dreamhouse]  | Sharing this information is equivalent to logging someone in under the current credential, resulting in unintended access and escalation of privilege.
[dreamhouse]  | For additional information, please review the authorization section of the https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_web_ [...]
10:17:34 ~/Documents/01_repo/dreamhouse-lwc  (main)
└─▶ $ metaOp.py local package mkPack --name deployTest --src "force-app/main/default/classes/FileUtilities.cls" "force-app/main/default/classes/FileUtilitiesTest.cls" "force-app/main/default/classes/GeocodingService.cls" "force-app/main/default/classes/GeocodingServiceTest.cls" "force-app/main/default/classes/PagedResult.cls" "force-app/main/default/classes/PropertyController.cls" "force-app/main/default/classes/SampleDataController.cls" "force-app/main/default/classes/TestPropertyController.cls" --delSrc "force-app/main/default/classes/TestSampleDataController.cls" 
Namespace(typeOp='local', locOp='package', packOp='mkPack', src=['force-app/main/default/classes/FileUtilities.cls', 'force-app/main/default/classes/FileUtilitiesTest.cls', 'force-app/main/default/classes/GeocodingService.cls', 'force-app/main/default/classes/GeocodingServiceTest.cls', 'force-app/main/default/classes/PagedResult.cls', 'force-app/main/default/classes/PropertyController.cls', 'force-app/main/default/classes/SampleDataController.cls', 'force-app/main/default/classes/TestPropertyController.cls'], delSrc=['force-app/main/default/classes/TestSampleDataController.cls'], name='deployTest')

>> Executing local-mkPack operation:
[deployTest] Re-Initialize Area: 'deployTest' and store old one inside: '00_Archive/PackStoreArea/deployTest
[deployTest] >> Delete PackStoreArea from file-system ...
[deployTest] 
[deployTest] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[deployTest] >> Convert from source-format deploy resources and store inside 'deployTest'...
[deployTest]  >$ sf project convert source --output-dir deployTest/metadataFormatPack\
[deployTest]  >$     --source-dir 'force-app/main/default/classes/GeocodingServiceTest.cls' 'force-app/main/default/classes/FileUtilities.cls' 'force-app/main/default/classes/Propert [...]
[deployTest] Source was successfully converted to Metadata API format and written to the location: /Users/ea_enel/Documents/01_repo/dreamhouse-lwc/deployTest/metadataFormatPack
[deployTest] 
[deployTest] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[deployTest] >> >> Generate 'destructiveChangesPost.xml' keeping priority for 'src' resource...
[deployTest]  >$ sf project generate manifest --output-dir deployTest/metadataFormatPack --name destructiveChangesPost.xml --source-dir 'force-app/main/default/classes/TestSampleData [...]
[deployTest] successfully wrote destructiveChangesPost.xml to deployTest/metadataFormatPack
[deployTest] 
[deployTest] >> Remove from destructiveChangesPost.xml the resource in common with package.xml...
[deployTest] 
[deployTest] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[deployTest] >> Generate source-format equivalent for current metadata-format pack ...
[deployTest]  >$ sf project convert mdapi --root-dir deployTest/metadataFormatPack --output-dir deployTest/sourceFormatPack --json
[deployTest] Conversion completed. Generated 16 sources.
[deployTest] 
[deployTest] >> Pack generated with PackStoreArea.mkPack(...)
[deployTest] Found follow Apex test classe:
[deployTest]    1) FileUtilitiesTest | 2) GeocodingServiceTest | 3) TestPropertyController
10:21:02 ~/Documents/01_repo/dreamhouse-lwc  (main)
└─▶ $ metaOp.py send validate --alias dreamhouse --pack deployTest
Namespace(typeOp='send', sendOp='validate', pack='deployTest', base_org='/Users/ea_enel/Documents/01_repo/dreamhouse-lwc/Orgs', alias=['dreamhouse'], timeout=60)

>> Executing send-validate operation:
[dreamhouse] Re-Initialize Area: 'Orgs/dreamhouse' and store old one inside: '00_Archive/OrgStoreArea/dreamhouse
[dreamhouse] >> Delete OrgStoreArea from file-system ...
[dreamhouse] >> Initializing Orgs/dreamhouse ...
[dreamhouse] 
[dreamhouse] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[dreamhouse] >> Searching org with Alias:= 'dreamhouse' in local DB...
[dreamhouse]  >$ sf org list auth --json
[dreamhouse] 
[dreamhouse] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[dreamhouse] >> Initializing authfile.json...
[dreamhouse]  >$ sf org display --target-org dreamhouse --verbose --json
[dreamhouse] Data extraction of dreamhouse Org complete.
[dreamhouse]  - Log inside Org: https://computing-saas-6400-dev-ed.scratch.my.salesforce.com
[dreamhouse]  - Using user:     test-aspfrg6dtixf@example.com
[dreamhouse]  - Api version:    60.0
[dreamhouse]  - Org alias:      dreamhouse
[dreamhouse] Warnings inside '/Users/ea_enel/Documents/01_repo/dreamhouse-lwc/Orgs/dreamhouse/authfile.json':
[dreamhouse]  | This command will expose sensitive information that allows for subsequent activity using your current authenticated session.
[dreamhouse]  | Sharing this information is equivalent to logging someone in under the current credential, resulting in unintended access and escalation of privilege.
[dreamhouse]  | For additional information, please review the authorization section of the https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_web_ [...]
[dreamhouse] Keeping from previous status:
[dreamhouse]    1) /Users/ea_enel/Documents/01_repo/dreamhouse-lwc/Orgs/dreamhouse/authfile.json
[dreamhouse] 
[dreamhouse] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[dreamhouse] >> Login to dreamhouse ...
[dreamhouse]  >$ sf org login sfdx-url --alias dreamhouse --sfdx-url-file Orgs/dreamhouse/authfile.json
[dreamhouse] (node:5534) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate veri [...]
[dreamhouse] (Use `node --trace-warnings ...` to show where the warning was created)
[dreamhouse] Successfully authorized test-aspfrg6dtixf@example.com with org ID 00D7Z0000005YDKUA2
[dreamhouse] 
[dreamhouse] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[dreamhouse] >> Start Validate operation inside Org dreamhouse ...
[dreamhouse]  >$ sf project deploy start --dry-run --target-org dreamhouse --ignore-warnings --json --async\
[dreamhouse]  >$     --metadata-dir 'Orgs/dreamhouse/metadataFormatPack'
(node:5572) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
[dreamhouse] 
[dreamhouse] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[dreamhouse] >> Show operation status for job '0Af7Z00003pBYbtSAG'
[dreamhouse]  >$ sf project deploy report --target-org dreamhouse --job-id 0Af7Z00003pBYbtSAG --wait 60
[dreamhouse] Status: {status} | ████████████████████████████████████████ | 0/0 Components{errorInfo}{testInfo}{trackingInfo}
[dreamhouse] (node:5594) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate veri [...]
[dreamhouse] (Use `node --trace-warnings ...` to show where the warning was created)
[dreamhouse] Status: In Progress | ████████████████████████████████████████ | 8/8 Components
[dreamhouse] Status: Succeeded | ████████████████████████████████████████ | 9/9 Components
[dreamhouse] 
[dreamhouse] Warning: ApexClass, FileUtilities, returned from org, but not found in the local project
[dreamhouse] Warning: ApexClass, FileUtilitiesTest, returned from org, but not found in the local project
[dreamhouse] Warning: ApexClass, GeocodingService, returned from org, but not found in the local project
[dreamhouse] Warning: ApexClass, GeocodingServiceTest, returned from org, but not found in the local project
[dreamhouse] Warning: ApexClass, PagedResult, returned from org, but not found in the local project
[dreamhouse] Warning: ApexClass, TestPropertyController, returned from org, but not found in the local project
[dreamhouse] Warning: ApexClass, PropertyController, returned from org, but not found in the local project
[dreamhouse] Warning: ApexClass, SampleDataController, returned from org, but not found in the local project
[dreamhouse] Warning: ApexClass, TestSampleDataController, returned from org, but not found in the local project
[dreamhouse] 0Af7Z00003pBYbtSAG... Succeeded
[dreamhouse] 
[dreamhouse] Deploy Info
[dreamhouse] ===================================================
[dreamhouse] | Key                      Value                    
[dreamhouse] | ──────────────────────── ──────────────────────── 
[dreamhouse] | checkOnly                true                     
[dreamhouse] | completedDate            2024-05-10T08:22:59.000Z 
[dreamhouse] | createdBy                0057Z00000Eujgr          
[dreamhouse] | createdByName            User User                
[dreamhouse] | createdDate              2024-05-10T08:22:54.000Z 
[dreamhouse] | done                     true                     
[dreamhouse] | id                       0Af7Z00003pBYbtSAG       
[dreamhouse] | ignoreWarnings           true                     
[dreamhouse] | lastModifiedDate         2024-05-10T08:22:59.000Z 
[dreamhouse] | numberComponentErrors    0                        
[dreamhouse] | numberComponentsDeployed 9                        
[dreamhouse] | numberComponentsTotal    9                        
[dreamhouse] | numberTestErrors         0                        
[dreamhouse] | numberTestsCompleted     0                        
[dreamhouse] | numberTestsTotal         0                        
[dreamhouse] | rollbackOnError          true                     
[dreamhouse] | runTestsEnabled          false                    
[dreamhouse] | startDate                2024-05-10T08:22:55.000Z 
[dreamhouse] | status                   Succeeded                
[dreamhouse] | success                  true                     
[dreamhouse] 
[dreamhouse] Deploy Options
[dreamhouse] ================================================
[dreamhouse] | Key              Value                         
[dreamhouse] | ──────────────── ───────────────────────────── 
[dreamhouse] | json             true                          
[dreamhouse] | async            true                          
[dreamhouse] | dry-run          true                          
[dreamhouse] | ignore-conflicts false                         
[dreamhouse] | ignore-errors    false                         
[dreamhouse] | ignore-warnings  true                          
[dreamhouse] | target-org       test-aspfrg6dtixf@example.com 
[dreamhouse] | api              SOAP                          
[dreamhouse] | wait             60 minutes                    
[dreamhouse] | isMdapi          true                          
[dreamhouse] | job-id           0Af7Z00003pBYbtSAG            
[dreamhouse] 
[dreamhouse] 
[dreamhouse] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[dreamhouse] >> Catch information in json form for job '0Af7Z00003pBYbtSAG'
[dreamhouse]  >$ sf project deploy report --target-org dreamhouse --job-id 0Af7Z00003pBYbtSAG --json
(node:5619) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
[dreamhouse] Report warnings:
[dreamhouse]  | ApexClass, FileUtilities, returned from org, but not found in the local project
[dreamhouse]  | ApexClass, FileUtilitiesTest, returned from org, but not found in the local project
[dreamhouse]  | ApexClass, GeocodingService, returned from org, but not found in the local project
[dreamhouse]  | ApexClass, GeocodingServiceTest, returned from org, but not found in the local project
[dreamhouse]  | ApexClass, PagedResult, returned from org, but not found in the local project
[dreamhouse]  | ApexClass, TestPropertyController, returned from org, but not found in the local project
[dreamhouse]  | ApexClass, PropertyController, returned from org, but not found in the local project
[dreamhouse]  | ApexClass, SampleDataController, returned from org, but not found in the local project
[dreamhouse]  | ApexClass, TestSampleDataController, returned from org, but not found in the local project
╔═══════════════════════════════╗
║ Validate summary:             ║
║  - dreamhouse      := Success ║
╚═══════════════════════════════╝
```

**Comment by mdonnalley** [comment] 2024-05-10 15:42
Ah I didn't realize that you were running `sf project convert source` first. I can replicate it now. Let me ask around and figure out if this is working as designed or not

**Comment by Alfystar** [comment] 2024-05-10 16:27
> Ah I didn't realize that you were running `sf project convert source` first. I can replicate it now. Let me ask around and figure out if this is working as designed or not

Don't worry, I didn't actually say it for granted, my mistake

**Comment by jshackell-sfdc** [comment] 2024-05-22 18:20
This issue is fixed in the 2.42.6 (May 22, 2024) release.

**Closed as completed by jshackell-sfdc** 2024-05-22 18:20 UTC
Labels: bug, validated

**Comment by Alfystar** [comment] 2024-06-04 09:29
Sorry @jshackell-sfdc 
but at today , with the release: `2.42.6 (May 22, 2024) [stable]`
Problem still show in out pipeline:

```none
Status: Succeeded \| 10/10 Components
--
Warning: ApexClass, GCDH_BS_CatalogHelper, returned from org, but not found in the local project
Warning: ApexClass, GCDH_BS_CatalogHelper_Test, returned from org, but not found in the local project
Warning: ApexClass, GCDH_CatalogHelper_Factory, returned from org, but not found in the local project
Warning: ApexClass, GCDH_CatalogHelper_Factory_Test, returned from org, but not found in the local project
Warning: ApexClass, GCDH_CatalogHelper_Input, returned from org, but not found in the local project
Warning: ApexClass, GCDH_CatalogHelper_Input_Test, returned from org, but not found in the local project
....
0AfbX000000CLa9SAG... Succeeded
```  

Same plan, same logic

**Comment by cristiand391** [comment] 2024-06-04 14:58
@Alfystar, could you try with sf v2.44.8 (current latest-rc)?

I've installed sf v2.42.6 and see it's using:
```
@salesforce/source-deploy-retrieve@11.4.3
```

when the fix for this landed in v11.4.4:
https://github.com/forcedotcom/source-deploy-retrieve/blob/main/CHANGELOG.md#1144-2024-05-14

The fix didn't get into nightly in time to be included in the sf v.2.42.6 as planned, sorry about that. We'll update the release notes for this.

**Comment by Alfystar** [comment] 2024-06-05 13:51
Received, no particular problem, it was just to show evidence.

We await the next stable release 😄

**Comment by jshackell-sfdc** [comment] 2024-06-05 16:32
Oops, sorry about that -- RNs fixed, will publish when today's RC goes out. Thanks for letting us know!

**Comment by jshackell-sfdc** [comment] 2024-06-05 18:56
This issue is addressed in version 2.44.8 (Jun 5, 2024). (hopefully this time for realsies!)

**Comment by Alfystar** [comment] 2024-06-06 12:20
Yes, I'm happy to confirm it 😄

**Comment by dschibster** [comment] 2024-07-17 07:05
I'm wondering because I have not encountered this error for a while but I am now encountering it again @jshackell-sfdc, could we have had a regression in the latest cli version again? I am seeing this warning come up again in my pipelines that prepare scratch orgs with metadata from our repo. The Global Value Sets are throwing the same warnings as they did before the fix.
