### ISSUE TITLE
Using sfdx source to retrieve profiles inconsistent result

### ISSUE THREAD

**Issue by manassanam08** [forcedotcom/cli#1624] opened 2022-07-12 17:28 UTC
Hello, I'm using salesforce cli to run basically "sfdx force:source:retrieve -m Profile:Admin", which I know technically sfdx is not that much compatible with profiles but, on a sandbox on a project, I got the object permissions and all that, but running that command on other sandboxes and my developer org brings only the user permissions, is that related to some org config or something? I'd love to know because I kinda like to use sfdx source for all I can.

 

Thanks in advance, I hope someone can help me out on this

Created below issue and they reverted me to create a bug report here. 
https://github.com/microsoft/vscode/issues/154903

Reproduce steps: 

Clone Azure repo.
Then Authorize a default org.
Then select a profile and right-click on that.
Click on "SFDX: Retrieve Source from Org".
Previously, there were around 10000 lines in the profile, now its just 29 lines and user permissions only. Its deleting other components.

**Comment by amtrack** [comment] 2022-07-13 10:03
@manassanam08

> Retrieving and pulling profiles behaves a little differently with source tracking.

https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_source_tracking_source_tracking_profiles.htm

**Comment by mshanemc** [comment] 2022-07-13 22:16
I don't like the way the API does it either.  I'm trying to get a better solution for this...please follow along on #1396 

duplicate of #1396

**Closed as completed by mshanemc** 2022-07-13 22:16 UTC
Labels: investigating
