### ISSUE TITLE
Failed to retrieve LightningComponentBundle metadata

### ISSUE THREAD

**Issue by ar-srinivas** [forcedotcom/cli#647] opened 2020-09-30 13:20 UTC
### Summary

sfdx source:retrieve is failing to retrieve LightningComponentBundle

### Steps To Reproduce:

sfdx force:source:retrieve -m LightningComponentBundle is failing with the following error.

{
  "status": 1,
  "name": "TypeError",
  "message": "Cannot read property 'fileName' of undefined",
  "exitCode": 1,
  "commandName": "SourceRetrieveCommand",
  "stack": "TypeError: Cannot read property 'fileName' of undefined\n    at Function.getMetadataFileNameFromBundleFileProperties ...
}

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Run sfdx force:source:retrieve -m LightningComponentBundle -u <username>

### Expected result

It should retrieve all the LightningComponentBundle metadata.

### Actual result

Failing with TypeError
{
  "status": 1,
  "name": "TypeError",
  "message": "Cannot read property 'fileName' of undefined",
  "exitCode": 1,
  "commandName": "SourceRetrieveCommand",
  "stack": "TypeError: Cannot read property 'fileName' of undefined\n    at Function.getMetadataFileNameFromBundleFileProperties ...
}

### Additional information

This is also failing with the same error even with manifest file on the command (-x package.xml)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.74.1-32db2396ed win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): @oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.9.2 (49.9.2)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ templates 49.9.1
├─ salesforce-alm 49.10.0
├─ custom-metadata 1.0.10
└─ apex 0.0.9
sfdx-cli 7.74.1 (core)
sfdx-codescan-plugin 1.0.4

**OS and version**: Windows 10

**Comment by shetzel** [comment] 2020-09-30 17:06
Duplicate of #563 
The fix will be in the next patch scheduled for tomorrow.

**Closed as completed by shetzel** 2020-09-30 17:06 UTC
