### ISSUE TITLE
sfdx force:web:auth:login (Authorize an Org) Does not work

### ISSUE THREAD

**Issue by NuAgeDan** [forcedotcom/cli#782] opened 2020-12-22 03:57 UTC
### Summary

Running SFDX Authorize an org does not work from VS Code, nor does running the same command from command prompt do anything. It simply runs without response.

### Steps To Reproduce:

1. Create a new project with manifest
2. Run SFDX: Authorize an Org. Nothing happens. No error is returned, no browser is opened. Changing the default browser has no effect. 
3. Open command prompt and try running sfdx force:auth:web:login --setalias "Name Here" --instanceurl https://test.salesforce.com

### Expected result

Browser opens to complete auth process. Edit: It works on an ancient version of Firefox (8 months out of date by now). Both Chrome and Edge do not work. Presumably a Chromium thing? Also both the plugins and CLI are on the latest version.

### Actual result

Nothing.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 7.82

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): 50.8

**OS and version**: Windows 10. Latest.

**Comment by peternhale** [comment] 2021-01-08 16:55
@NuAgeDan Thank for reporting this issue.

I have been unable to reproduce this issue. My sfdx installation on Windows 10 is:
```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.7.0 (core)
├─ schema 1.0.1 (core)
├─ salesforce-alm 50.7.0 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.82.0 (core)
```
I tried both scenarios with the command line attempts run outside of a sfdx project and the VSCode attempts using a new project created with `sfdx force:project:create -n test`. For VSCode I tried both production and test environments.

All attempts resulted in the default browser opening at the specified URL. Browsers used MS Edge, Chrome and FireFox.

Is there any other details you might provide to assist me in reproducing the issue you are experiencing?

**Comment by NuAgeDan** [comment] 2021-01-08 17:07
I haven't be able to replicate it either today. I think its possible it was a chromium issue since both Chrome / Edge had problems but Firefox worked and it seems to be fixed with the same cli / plugin versions

**Comment by peternhale** [comment] 2021-01-08 17:09
@NuAgeDan, thank you for the additional info. I am going to close this issue for now. If it reoccurs or you find additional info, please feel free to reopen the issue.

**Closed as completed by peternhale** 2021-01-08 17:09 UTC
Labels: env:windows
