### ISSUE TITLE
Summer '20 force:source:deploy and force:source:retrieve fail for components that use shared CSS LWC

### ISSUE THREAD

**Issue by lindsayholmes-gears** [forcedotcom/cli#492] opened 2020-07-16 01:09 UTC
### Summary
I created a CSS-only LWC to share CSS among multiple LWCs. As soon as other LWCs include the code to import the shared CSS, they can no longer be deployed to or retrieved from the org using the CLI (I've used Workbench as a workaround). The message received reads:
> ERROR running force:source:retrieve:  Cannot read property 'fileName' of undefined

### Steps To Reproduce:
**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)
Files created in repository [sharedCssBug](https://github.com/lnholmes/sharedCssBug)

To reproduce, follow steps in [release notes](https://releasenotes.docs.salesforce.com/en-us/summer20/release-notes/rn_lwc_css_share.htm) exactly.

### Expected result
One should successfully be able to retrieve and deploy myComponent using force:source:deploy and force:source:retrieve.

### Actual result
When running force:source:retrieve, the following error message is received:
> ERROR running force:source:retrieve:  Cannot read property 'fileName' of undefined

Results from --loglevel trace: [retrieveTrace.txt](https://github.com/forcedotcom/cli/files/4928735/retrieveTrace.txt)
Results from --dev-debug: [retrieveDebug.txt](https://github.com/forcedotcom/cli/files/4928721/retrieveDebug.txt)

When running force:source:deploy, the following error message is received:
> No MODULE named markup://c:cssLibrary found : [markup://c:myComponent]

Results from --loglevel trace: [deployTrace.txt](https://github.com/forcedotcom/cli/files/4928737/deployTrace.txt)
Results from --dev-debug: [deployDebug.txt](https://github.com/forcedotcom/cli/files/4928738/deployDebug.txt)

NOTE: the attached text documents with debug/trace results are from my org where I initially experienced the problem, so the names of components don't match up to the samples. All the trace/debug docs can also be found in the linked repository above.

### Additional information
**SFDX CLI Version**: sfdx-cli/7.65.6-23e8b7f47e win32-x64 node-v12.13.0

**SFDX plugin Version**: salesforcedx 48.22.11 (core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core) 
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core) 
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.4.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.9
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
**salesforcedx 48.22.11 (core)**
├─ salesforce-alm 48.24.3 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ custom-metadata 1.0.4 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdx-cli 7.65.6 (core)

**OS and version**: Windows 10 Business

**Comment by GH4Arlene** [comment] 2020-07-21 20:15
Let us know if you need another example.  We are seeing the same behavior on force:source:deploy.

Update: 
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.2.3 (core)
├─ salesforce-alm 49.3.0 (core)
├─ salesforcedx-templates 48.32.0 (core)
├─ custom-metadata 1.0.7 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdx-cli 7.66.2 (core)

**Comment by shetzel** [comment] 2020-07-21 21:01
`ERROR running force:source:retrieve: Cannot read property 'fileName' of undefined` is definitely a theme with lots of recent issues so we'll get it fixed asap.  Thank you!

**Comment by peternoges** [comment] 2020-07-29 17:57
I too am getting UNKNOWN_EXCEPTION during force:source:retrieve against a partial copy sandbox (The org is on api version 49.0,  / summer '20).  

The metadata retrieve operation failed: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 588521454-54462 (-1001565770)

I am actively troubleshooting, but at this point am unsure of the root cause.

**Comment by peternoges** [comment] 2020-07-29 18:13
I too am getting UNKNOWN_EXCEPTION during force:source:retrieve against a partial copy sandbox (The org is on api version 49.0, / summer '20).

The metadata retrieve operation failed: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1264699478-41811 (-1001565770)

BTW im using the latest version of sfdx at least as of 2020-07-29T11:10:44-0700 

At this point in the troubleshooting process I cannot find the metadata to blame, so next im loosening my forceignore file to see if that fixes it.  I will post back here if i find the reason for the UNKNOWN_EXCEPTION that i am seeing.

**Comment by saddankiSFDC** [comment] 2020-08-30 15:40
Is there any ETA on this fix?

**Comment by jmleep** [comment] 2020-09-11 12:25
Also looking for an ETA on this issue... The only workaround is to deploy the shared CSS component every time you deploy any component that imports it, but you must use the CLI and not the VSCode extensions. It's very frustrating.

**Comment by nitinparasa** [comment] 2020-09-21 08:31
+1 on this. A fix will be much appreciated!

**Comment by shetzel** [comment] 2020-09-21 16:05
This looks the same as #496 and #400.  The fix will be in the next patch release.

**Comment by mshanemc** [comment] 2021-12-06 15:24
#496 and #400 are closed now, so I'm closing this one.

**Closed as completed by mshanemc** 2021-12-06 15:24 UTC
Labels: bug
