### ISSUE TITLE
Deprecated warning message part of stdout instead of stderr resulting in invalid json response

### ISSUE THREAD

**Issue by jguay** [forcedotcom/cli#1896] opened 2023-01-25 09:48 UTC
sfdx version [7.184.2](https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71842-jan-19-2023-stable) using deprecated function and redirecting stderr to `/dev/null`, the output is invalid json as the json is prefixed by some non json text `Warning...` that does not respect json formatting rules: 
```
$ sfdx force:data:soql:query -r json -q "${query}" 2>/dev/null | head -2
Warning: The "force data soql query" command has been deprecated. Use "data query" instead.
{
```

This deprecation warning is a breaking change, assume I don't control the sfdx version, the new `data query` does not work on older sfdx version and we now have to do 2 things to fix this : 
1. The main and immediate workaround we have put in place is to remove the first line of json output if it starts with `Warning` - I expect warning should be sent to `stderr` then there would not be any issue (we capture stderr to logs but that would not break automations)... 
2. And we'll add code to check sfdx version is lower or higher than `7.184.2` to call the new methods which did not exist in previous version

**Comment by WillieRuemmele** [comment] 2023-01-25 15:34
Hi @jguay , thanks for reporting this issue! I was able to reproduce it, but also found a workaround. 
```
➜  dreamhouse-lwc git:(main) ✗  hub:(GLOBAL - DevHub) scratch:(test-94etztt3i5x5@example.com)
 ➜  sfdx force:data:soql:query -q "SELECT MemberName, MemberType FROM SourceMember" --json -t 2>/dev/null | head -2  
{
  "status": 0,
➜  dreamhouse-lwc git:(main) ✗  hub:(GLOBAL - DevHub) scratch:(test-94etztt3i5x5@example.com)
 ➜  sfdx force:data:soql:query -q "SELECT MemberName, MemberType FROM SourceMember" -r json -t 2>/dev/null | head -2
Warning: The "force data soql query" command has been deprecated. Use "data query" instead.
{
```
instead of using `-r json`, just using the `--json` flag

**Comment by jguay** [comment] 2023-01-25 22:15
Thank you @WillieRuemmele `--json` option works perfectly all warnings end up in JSON payload in array `.warnings[]`, this is the exact behaviour we needed for our automation

**Comment by mshanemc** [comment] 2023-02-13 21:45
duplicate of #1926

**Closed as completed by mshanemc** 2023-02-13 21:45 UTC
Labels: bug
