### ISSUE TITLE
Scratch Org Feature not Enabled using Org Shape

### ISSUE THREAD

**Issue by pclements12** [forcedotcom/cli#901] opened 2021-03-05 16:56 UTC
### Summary

When using the Org Shape (beta) feature, sometimes the `ContactsToMultipleAccounts` feature from the source org isn't enabled in the target scratch org.

### Steps To Reproduce:

1. Create an Org Shape from an Org that has the `ContactsToMultipleAccounts` Feature enabled
2. Create a new SFDX Project and use the Org Shape in the `project-scratch-def.json`:
```
{
  "orgName": "bug-org",
  "sourceOrg": "00Dj0000000SOURCEORGID"
}
```
3. Create a scratch org using the CLI:
```sfdx force:org:create -f config/project-scratch-def.json -a feature-bug```

### Expected result

When the scratch org is created, it has the `ContactsToMultipleAccounts` Feature enabled and allows pushing code that relies on this feature (Presence of the `AccountContactRelation` object exists)

### Actual result

Sometimes the feature is enabled, and sometimes it isn't. It's not clear when it is or is not enabled in the Scratch Org. 
In come cases:
- The UI and the `Account.settings` metadata will indicate the setting is enabled, but pushes will fail (lack of `AccountContactRelation` Apex class)
- The UI and `Account.settings` metadata indicate the feature is NOT enabled, (pushes also fail)
- The UI and `Account.settings` metadata indicate the feature is enabled, AND pushes work

We observe the issue each time when we try to push Apex code into the org that relies on the `AccountContactRelation` object that only exists when this feature is enabled and the push fails.

The issue seems to present itself randomly. More than half of the scratch orgs we create in this way are unusable.
We only started to see this issue a few weeks ago following the Spring '21 release of SalesForce.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 
7.85.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
salesforcedx 50.15.0 (core)

**OS and version**: 
Observed on developer systems: MacOS Catalina 10.15.7, Windows 10, 
and CI/CD server: Alpine Linux docker image

**Comment by bkwdesign** [comment] 2021-09-08 19:04
I spun up two Winter '22 orgs which point to the same shape org .. my `project-scratch-def.json` in addition to pointing at the shape, has the old-school feature-enablement stuff in it, too. My org from yesterday has the `AccountContactRelation` table and the one I spun up today does not

```
{
  "orgName": "My Scratch",
  "sourceOrg": "00D2blah-blah-blah", 
  "features": ["Communities","Sites","MarketingUser","ServiceCloud","SalesUser","ServiceUser","ContactsToMultipleAccounts","FieldService:2"],
  "description":"Sometimes it works",
  "adminEmail": "myself@mycorporation.com",
  "hasSampleData": true,
  "settings": 
  {
    "accountSettings": {
      "enableRelateContactToMultipleAccounts": true
    },
    "lightningExperienceSettings": {
        "enableS1DesktopEnabled": true
    },
    "mobileSettings": {
        "enableS1EncryptedStoragePref2": false
    },
    "pathAssistantSettings": {
        "pathAssistantEnabled": true
    },
    "fieldServiceSettings": { 
      "fieldServiceOrgPref": true ,
      "doesShareSaWithAr":true,
      "serviceAppointmentsDueDateOffsetOrgValue":7,
      "enableWorkOrders":true
    },
    "chatterSettings": {
      "enableChatter":true
    },
    "apexSettings": {
        "enableCompileOnDeploy": false
    }
  }
}
```

**Comment by daveespo** [comment] 2021-09-08 19:26
@bkwdesign  -- Just checking here -- you've been able to get Org Shape (the one you specify using `sourceOrg` in the scratch org definition file) in conjunction with `release=Preview` to get a preview (Winter '22) scratch org? We've never been able to get these two parameters to work at the same time.

**Comment by bkwdesign** [comment] 2021-09-08 19:34
@daveespo - I haven't specified `release=Preview` anywhere - i'm just noticing that when I navigate to my scratch orgs they have the little splash graphic indicating `22

The definition I posted above is invoked with:
```
sfdx force:org:create -f config\project-scratch-def.json --setalias Scratch1 --durationdays 7 --setdefaultusername --json --loglevel fatal --wait 9600
```

**Comment by daveespo** [comment] 2021-09-09 18:10
That's wild .. is your DevHub org also on Winter '22? (Which I think is only possible if you're using a trial DevHub since no production orgs are on W'22 yet)

**Comment by bkwdesign** [comment] 2021-09-10 10:30
I think my company is in a preview window where our sandboxes (should we spin one up) are on Winter 22 - this must also apply to our scratch orgs. The preview is different depending on where your underlying org server is hosted. Below is an email I got:
————— 
We're contacting you because you're identified as a System Administrator for an instance of Salesforce that's getting upgraded to the Winter '22 Release. 

The Salesforce Winter '22 release is coming soon. Use your sandbox to get early access to new features and test your configurations before the production upgrade. Here's how: 
The Winter '22 sandbox preview window is scheduled to begin August 27, 2021. You must have an active sandbox on a preview instance before August 26, 2021 to take advantage of the Winter '22 preview. In most cases, you don't need to do anything because your sandbox is already on a preview instance.
Read the Winter '22 Sandbox Preview Instructions and use the [Sandbox Preview Guide](http://click.mail.salesforce.com/?qs=e59465adb7cfb2bdf53139270e93a1732e778cc4a55d9d6174a8319f922312b4971e41aef28d90c9d81aebd22249ad8269af31fa045c63c3) to see whether to take action. The Sandbox Preview Guide simplifies how you plan if and when you need to trigger a refresh for your existing Sandbox orgs. Type in your Sandbox instance (CSx) to get started.
If you still have questions about your sandbox options for Winter '22, open a support case via Salesforce Help.

**Comment by AndreyShestakovACN** [comment] 2022-06-16 19:14
Hello! 
I justed the org shape functionality today. 
1. I created a developer org, where I enabled the feature:
- Account Settings -> Contacts to Multiple Accounts (Allow users to relate a contact to multiple accounts)
2. At the org I enabled DevHub and Org Shape, where I provide the org Id of this same org
3. Created scratch org definition file
``` json
{
    "orgName": "Test Org",
    "sourceOrg": "00D##########"
}
```
4. Created the scratch org
> sfdx force:org:create -f config/project-scratch-def-shape.json -a OSTSO1 -v OrgShapeTest --durationdays 1 --wait 30
5. Once the scratch org has been created, opened it and verified the `Contacts to Multiple Accounts` feature is not enabled.

This may be related to the issue logged earlier #1537

**Comment by shetzel** [comment] 2022-06-20 18:31
This is a known serverside issue and the appropriate team is tracking internally with W-9529783 and W-9604466.  Since this is not an issue with the CLI I'm closing this issue.  Feel free to contact support for anything addtional.

**Closed as completed by shetzel** 2022-06-20 18:31 UTC
Labels: owned by another team, investigating

**Comment by FabienTaillon** [comment] 2022-06-21 07:41
For anyone interested there are 2 Known Issues about it, one for Org Shape [here](https://trailblazer.salesforce.com/issues_view?id=a1p4V000001s8OlQAI), and a second one for Scratch Org [here](https://trailblazer.salesforce.com/issues_view?id=a1p3A000001PYYlQAO) (because the issue is actually not limited to Org Shape).
