### ISSUE TITLE
skipRecordTypeSelect not set via MetaData

### ISSUE THREAD

**Issue by jhgihub0** [forcedotcom/cli#2936] opened 2024-06-21 15:17 UTC
We are currently using the following version of Salesforce CLI

`@salesforce/cli/2.46.6 darwin-arm64 node-v20.14.0`

We are using these commands to deploy the metadata to the sandbox:

```
sf org login web --alias OrgAlias --instance-url https://test.salesforce.com
project deploy start --target-org OrgAlias --wait 120 --test-level "NoTestRun" --source-dir ./sfdx-source
sf org logout --target-org OrgAlias --no-prompt

```

In our Escalations object, we are trying to set the "Skip record type selection page" option

![image](https://github.com/forcedotcom/cli/assets/59979805/3961ee31-d0cb-44ee-9b37-6b0e0b5a93db)

Our metadata looks like this

![image](https://github.com/forcedotcom/cli/assets/59979805/c5a3265e-5466-4f32-969b-9d89e8a78606)

It is not being set in the sandbox when we do the metadata deployment

Pulling the metadata works fine using this command:

`sf project retrieve start --target-org OrgAlias --source-dir sfdx-source --wait 180   `

If its unchecked, the metadata pulls as 

`<skipRecordTypeSelect>false</skipRecordTypeSelect>`

If its checked, its 

`<skipRecordTypeSelect>true</skipRecordTypeSelect>`

Thank you.

**Comment by jhgihub0** [comment] 2024-06-21 15:23
```
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.46.6",
  "nodeVersion": "node-v20.14.0",
  "osVersion": "Darwin 23.5.0",
  "rootPath": "/Users/work/.local/share/sf/client/2.46.6-191291b",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.1.2 (core)",
    "@oclif/plugin-commands 4.0.2 (core)",
    "@oclif/plugin-help 6.2.1 (core)",
    "@oclif/plugin-not-found 3.2.3 (core)",
    "@oclif/plugin-plugins 5.2.4 (core)",
    "@oclif/plugin-search 1.1.2 (core)",
    "@oclif/plugin-update 4.3.5 (core)",
    "@oclif/plugin-version 2.2.3 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.5 (core)",
    "@oclif/plugin-which 3.2.2 (core)",
    "@salesforce/cli 2.46.6 (core)",
    "apex 3.1.18 (core)",
    "auth 3.6.21 (core)",
    "data 3.4.6 (core)",
    "deploy-retrieve 3.9.4 (core)",
    "info 3.3.6 (core)",
    "limits 3.3.12 (core)",
    "marketplace 1.2.12 (core)",
    "org 4.2.1 (core)",
    "packaging 2.4.6 (core)",
    "schema 3.3.11 (core)",
    "settings 2.3.1 (core)",
    "sobject 1.4.11 (core)",
    "source 3.4.2 (core)",
    "telemetry 3.4.0 (core)",
    "templates 56.2.11 (core)",
    "trust 3.7.5 (core)",
    "user 3.5.13 (core)"
  ]
}

```

**Comment by shetzel** [comment] 2024-06-24 21:25
@jhgihub0 - Did this behavior ever work with the CLI?  In other words, is this a regression from a previous version of the CLI that used to work?  I suspect that this is broken on the server side and that specific property is being ignored.  Are you able to deploy a change to that property either way?  I.e, changing it from true (in the org) to false, or from false (in the org) to true.

**Comment by jhgihub0** [comment] 2024-06-25 19:48
I tried previous versions and I could not find a version that ever worked.

**Comment by shetzel** [comment] 2024-06-25 21:39
The CLI is sending the correct metadata changes, so this issue is due to something outside of CLI control.  I suspect that the server side team who owns that metadata has a bug that does not apply changes to that field.

The best path forward is to create a support case so the proper team can prioritize and fix the bug.  Reference: https://help.salesforce.com/s/articleView?id=000393090&type=1

Tell support about this issue and let them know that the internal team to contact is called, "Platform Actions".  Apologies, but this is not an issue that can be fixed by the Salesforce CLI team.

**Closed as completed by shetzel** 2024-06-25 21:39 UTC
Labels: more information required, investigating, validated
