### ISSUE TITLE
Stray node processes using 100% CPU

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#365] opened 2020-04-13 03:19 UTC
### Summary

Within last month I've noticed stray node processes using 100% of CPU. Happens from both - cli and Illuminated Cloud.

### Steps To Reproduce:

Unclear, but most likely from source push.

### Additional information

See screenshot for the example.
<img width="973" alt="Screen Shot 2020-04-13 at 3 14 09 PM" src="https://user-images.githubusercontent.com/7092409/79089370-03c68980-7d9a-11ea-8aab-9833c42c10e4.png">

Node version in the path `v10.15.3`. Node global version `v10.13.0`.
Sfdx version `sfdx-cli/7.53.0-839fc82926 darwin-x64 node-v10.15.3`
Macos catalina `10.15.4 (19E266)`

**Comment by sjurgis** [comment] 2020-04-22 03:55
All open files:

```
open files 2

cwd
/Users/heyoo/workspace/DND/sfdx
txt
/Users/heyoo/.local/share/sfdx/client/7.53.0-839fc82926/bin/node
txt
/Library/Preferences/Logging/.plist-cache.ARV17fxz
txt
/usr/lib/dyld
0
/dev/null
1
/dev/null
2
/dev/null
3
count=0, state=0xa
4
->0x7442b8cc4b98fc74
5
->0x8932d87497f6c71f
6
->0x51da44eddc63ee08
7
->0x8feff2bb16f681d0
8
->0xd6240756496724f2
9
->0x8302bf8524a25230
10
count=0, state=0
11
->0x5f729b67aacd5b7e
12
->0x95a33a073dfc536c
13
->0x1af8b3d3cdcc6b73
14
->0xc833379fa5b5610b
15
count=0, state=0xa
16
->0xeba2cf09ffa5d490
17
->0x1c32187ba77528cf
18
->0x8e3b08deb3432707
19
->0x887b55ce89a3c499
20
/private/var/folders/bd/gmf8bv6s2qgd_nbz53fp1l300000gn/T/sfdx-analytics/analytics-1c429bc9e35c3a040c12e9006b7f2b3b2cdb366b.log
21
/Users/heyoo/.sfdx/sfdx.log
22
23
/dev/null
25
->0x54ab126eaa4f456f
26
[ctl com.apple.netsrc id 7 unit 62]
28
[ctl com.apple.netsrc id 7 unit 60]
```

Log from sfdx.log for the pid:

```
{"name":"sfdx","hostname":"cyborg-geesling.local","pid":14470,"level":60,"msg":"","time":"2020-04-22T03:44:37.619Z","v":0}
{"name":"sfdx","hostname":"cyborg-geesling.local","pid":14470,"log":"TelemetryReporter","level":60,"msg":"","time":"2020-04-22T03:44:37.620Z","v":0}
{"name":"sfdx","hostname":"cyborg-geesling.local","pid":14470,"log":"AppInsights","level":60,"msg":"","time":"2020-04-22T03:44:37.620Z","v":0}
{"name":"sfdx","hostname":"cyborg-geesling.local","pid":14470,"log":"Org","level":60,"msg":"","time":"2020-04-22T03:44:37.620Z","v":0}
{"name":"sfdx","hostname":"cyborg-geesling.local","pid":14470,"log":"AuthInfo","level":60,"msg":"","time":"2020-04-22T03:44:37.620Z","v":0}
{"name":"sfdx","hostname":"cyborg-geesling.local","pid":14470,"log":"crypto","level":60,"msg":"","time":"2020-04-22T03:44:37.620Z","v":0}
{"name":"sfdx","hostname":"cyborg-geesling.local","pid":14470,"log":"keyChain","level":60,"msg":"","time":"2020-04-22T03:44:37.620Z","v":0}
```
the `/private/var/folders/bd/gmf8bv6s2qgd_nbz53fp1l300000gn/T/sfdx-analytics/analytics-1c429bc9e35c3a040c12e9006b7f2b3b2cdb366b.log` doesnt seem to exist.

**Comment by amphro** [comment] 2020-04-22 06:12
I'm scratching my head at what could be causing this. I can't get the process to hang on the same versions you are running on.

From your logs, it seems like it is most likely telemetry. I don't see anything obvious in the code that would cause a high CPU zombie. How consistent if this for you? I bet setting `SFDX_DISABLE_TELEMETRY` would prevent it. I would like to find the root cause but we would either need a repo or do a video call to debug it.

**Comment by sjurgis** [comment] 2020-05-05 23:31
> I'm scratching my head at what could be causing this. I can't get the process to hang on the same versions you are running on.
> 
> From your logs, it seems like it is most likely telemetry. I don't see anything obvious in the code that would cause a high CPU zombie. How consistent if this for you? I bet setting `SFDX_DISABLE_TELEMETRY` would prevent it. I would like to find the root cause but we would either need a repo or do a video call to debug it.

Thanks @amphro - that seemed to work. Not sure if I want to help fixing telemetry :D
I guess I could call you when it happens again, but I don't have a good repro - thats the main problem.

**Comment by amphro** [comment] 2020-05-06 01:07
Well glad that solved it for you. Now that I know disabling telemetry solved it for you we could probably add another setting to add some local logging to help solve it. I totally get you not feeling inclined to help solve telemetry though.

**Comment by mshanemc** [comment] 2021-03-26 16:01
telemetry has been substantially updated.  I'm closing this issue (please reopen, or do a new one if it happens again)

**Closed as completed by mshanemc** 2021-03-26 16:01 UTC
