### ISSUE TITLE
sfdx force:package:version:create throws “ERROR running force:source:retrieve: Cannot read property 'record' of undefined

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#586] opened 2020-08-30 17:22 UTC
### Summary

`sfdx force:package:version:create` throws “ERROR running force:source:retrieve: Cannot read property 'record' of undefined

### Steps To Reproduce:

- Run ` sfdx force:package:version:create -d force-app -e bla -p testing_package_aws_2 -a testing_package_aws_2_1.1 -n 1.1.0.0 -x -v devhub`

- Wait the error message to show up

- Run `sfdx plugins:install salesforcedx@49.2.3` and wait it to finish with success

- The run again ` sfdx force:package:version:create -d force-app -e bla -p testing_package_aws_2 -a testing_package_aws_2_1.1 -n 1.1.0.0 -x -v devhub`

- Wait to see the same error message as before

- Install versions `7.70.1` , `7.72.0` and try to create a package version with each version.

- Check it alwas throws the same error.

- Downgrade to version `7.69.0` and see the error does not happen
`
### Expected result

The command should create a package version

### Actual result

The command throws an error

### Additional information

![image](https://user-images.githubusercontent.com/55927613/91665411-be49f500-eacb-11ea-8d25-3dac2eb177c2.png)

I also tried this command `sfdx plugins:install salesforcedx@49.2.3` (as explained here #581) before creating the package version but it did not work.

The same error happens on version: `7.70.1` , `7.72.0`.  

The error does not happen on version: `7.69.0`

**Comment by shetzel** [comment] 2020-08-31 15:53
Duplicate of #581 

The fix is coming in this week's patch release.  Sorry for the inconvenience!

**Closed as completed by shetzel** 2020-08-31 15:53 UTC

**Comment by AllanOricil** [comment] 2020-08-31 17:28
> Duplicate of #581
> 
> The fix is coming in this week's patch release. Sorry for the inconvenience!

@shetzel no problem! Thank you for the help
