### ISSUE TITLE
Unable to authorize orgs

### ISSUE THREAD

**Issue by dvon88** [forcedotcom/cli#834] opened 2021-02-05 13:51 UTC
I am unable to authorize any org. I have tried running through VSCode and through the terminal. I can get to the Allow Access page and click yes, but then it redirects to localhost 1717 and eventually it stops and gives me "ERR_EMPTY_RESPONSE." This happens for all orgs, all browsers. I have already tried the steps in this link and it doesn't not work either...
https://trailblazer.salesforce.com/issues_view?id=a1p3A0000003dkDQAQ

### Steps To Reproduce:

Open VSCode -> create project -> authorize an org -> enter username and password -> allow access
OR
Do it in the terminal

### Expected result

Authorized org

### Actual result

After several minutes, it does not connect and says "ERR_EMPTY_RESPONSE"

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.84.2-a2868a68d5 linux-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 50.13.3 (core)
├─ user 1.0.5 (core)
├─ schema 1.0.3 (core)
├─ limits 1.0.2 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 50.4.0 (core)
├─ salesforce-alm 50.13.1 (core)
├─ custom-metadata 1.0.11 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.84.2 (core)

**OS and version**:
Ubuntu 20.04.2 LTS

**Comment by AllanOricil** [comment] 2021-02-05 15:43
I have the this problem with a Raspberry Pi running Ubuntu.

**Comment by ErikChase** [comment] 2021-02-05 17:57
Similarly, we are running into an issue with our CI/CD tool when it is trying to authorize an org using the `force:auth:jwt:grant` command.  It's giving us an error saying `Warning: force:auth:jwt:grant is not a sfdx command.`. Since the 50.13.3 release was re-rolled out today, I'm wondering if this is related to the deprecation of force:auth in favor of the auth plugin?

**Comment by WillieRuemmele** [comment] 2021-02-05 18:28
Hi @dvon88 @ErikChase we just published a new release today, and a `latest-rc` tag, try the `latest-rc` with `npm install sfdx-cli@latest-rc --global` and see if that fixes it. As for the alias between `force:auth:` and just `auth` commands that should've been resolved

**Comment by ErikChase** [comment] 2021-02-05 19:25
That has resolved the issue for me!  Thank you so much!

**Comment by dvon88** [comment] 2021-02-06 10:04
@WillieRuemmele that did not fix the issue. I ended up reinstalling linux and that "fixed" it. I'll mark the issue as closed since I cannot reproduce it anymore, but this is definitely not a fix. I should not have to reinstall my operating system to fix an issue with the CLI.

**Comment by dvon88** [comment] 2021-02-07 08:59
@WillieRuemmele  nevermind, I can still reproduce the issue. I am now again trying to update to the latest release and getting a timeout error during the update when trying to fetch https://registry.npmjs.org/resolve.

Issue is still open. Still broken. Was only able to authorize one org.

**Comment by SwanGlTHUB** [comment] 2021-02-08 09:55
@WillieRuemmele 
It didn't work for me(

**Comment by the1mattkaufman** [comment] 2021-02-11 05:51
@WillieRuemmele I've been having the same issue on Debian
sfdx-cli/7.86.3 linux-x64 node-v14.15.5

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.7 (core)
config 1.2.4 (core)
generator 1.1.5 (core)
salesforcedx 50.16.1 (core)
├─ limits 1.0.3 (core)
├─ schema 1.0.3 (core)
├─ user 1.0.11 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ templates 50.4.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 50.16.1 (core)
sfdx-cli 7.86.3 (core)
telemetry 1.0.1 (core)

Debian GNU/Linux 10
Linux version 5.4.74-10576-gb6cc41974db3

**Comment by dpuza-formativ** [comment] 2021-02-14 01:07
I frequently have this issue.  For a while I had luck setting my default browser to Firefox when I auth (I normally use Chrome).  But then I got the same issue on Firefox too.  Then I worked around it using Edge.

**Comment by mdonnalley** [comment] 2021-02-16 22:31
Duplicate of https://github.com/forcedotcom/cli/issues/783

**Closed as completed by mdonnalley** 2021-02-16 22:31 UTC
Labels: duplicate, tracked elsewhere
