### ISSUE TITLE
Can't deploy component with shared CSS

### ISSUE THREAD

**Issue by pozil** [forcedotcom/cli#627] opened 2020-09-21 11:50 UTC
### Summary

In LWC we can [share CSS style sheet betweeen components](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.create_components_css_share).

This works fine and is demonstrated in our [LWC Recipes  sample app](https://github.com/trailheadapps/lwc-recipes).
However, this fails when deploying components one by one.

### Steps To Reproduce:

I've extracted 3 components from LWC recipes to simplify repro steps but this can be reproduced on the official repo.

Running these commands exposes the bug:
```sh
git clone git@github.com:pozil/css-sharing-bug.git
cd css-sharing-bug
sfdx force:org:create -f config/project-scratch-def.json -s -a css-sharing-issue

sfdx force:source:deploy -p force-app/main/default/lwc/contactTile
sfdx force:source:deploy -p force-app/main/default/lwc/cssLibrary
sfdx force:source:deploy -p force-app/main/default/lwc/compositionBasics
```

### Expected result

No errors, components are deployed.

### Actual result

Last command (`compositionBasics` deployment) fails with:
```
No MODULE named markup://c:cssLibrary found : [markup://c:compositionBasics]
```

### Additional information

What's intersting is that a full deploy of the project works fine:
```sh
sfdx force:source:deploy -p force-app
```

**SFDX CLI Version**:
```
sfdx-cli/7.74.1-32db2396ed darwin-x64 node-v12.18.3
```

**SFDX plugin Version**:
```
@oclif/plugin-autocomplete 0.2.0
@salesforce/lwc-dev-server 2.5.1
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9
salesforcedx 49.10.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ templates 49.9.1
├─ custom-metadata 1.0.10
├─ apex 0.0.9
└─ salesforce-alm 49.11.0
```

**OS and version**:
macOS Catalina

**Comment by pozil** [comment] 2020-09-21 11:52
Could be related to #492

**Comment by shetzel** [comment] 2020-09-21 16:29
Yes, it's related to 492.  It'll be fixed in the next patch release along with the all the other retrieve problems with css only LWCs.  Thank you for the detailed issue writeup.  If you don't mind, I'll close this one and work off 492.

**Comment by shetzel** [comment] 2020-09-21 18:19
I'm keeping this issue open since it has an easy reproducer and it is unrelated to the retrieve bug mentioned in other issues.  It's a LWC serverside problem, not a CLI problem so it will be tracked internally with that team.  Thank you @pozil for this excellent issue report!

**Comment by shetzel** [comment] 2020-09-21 18:44
Tracked internally as W-8107022

**Comment by jclark-dot-org** [comment] 2020-10-15 16:11
@shetzel  I'm seeing the same issue with a `force:source:push` for an LWC component with a CSS file that `@include`s a shared CSS File; a workaround is to make any change, including whitespace, to the shared CSS, so that the push includes it.   Is this included in this bug or should I file another?

**Comment by shetzel** [comment] 2020-10-15 20:22
@jclark-dot-org - yes, the usecase you detailed should be included in the bug fix.  Note that it's a serverside issue so the fix won't come in a CLI patch release.  It'll be part of a Salesforce major release.

**Comment by mshanemc** [comment] 2023-02-13 19:39
this was delivered a few year ago

**Closed as completed by mshanemc** 2023-02-13 19:39 UTC
Labels: bug, tracked elsewhere, owned by another team
