### ISSUE TITLE
sfdx force:source:retrieve -m LightningComponentBundle

### ISSUE THREAD

**Issue by sf9y** [forcedotcom/cli#503] opened 2020-07-20 08:58 UTC
### Summary

_Short summary of what is going on or to provide context_.

sfdx force:source:retrieve -m LightningComponentBundle fails with the error

Cannot read property 'fileName' of undefined

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  sfdx force:source:retrieve -m LightningComponentBundle

### Expected result

_Describe what should have happened_.

Retrieves the source

### Actual result

_Describe what actually happened instead_.

Nothing retrieved

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.66.2 darwin-x64 node-v13.10.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

salesforcedx 49.2.3 (core)
├─ salesforce-alm 49.3.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforcedx-templates 48.32.0 (core)
└─ custom-metadata 1.0.7 (core)
sfdx-cli 7.66.2 (core)

**OS and version**:
macOS

**Comment by shetzel** [comment] 2020-08-05 17:20
Duplicate of #496

**Closed as completed by shetzel** 2020-08-05 17:20 UTC
Labels: duplicate
