### ISSUE TITLE
SFDX: force:convert not working for remoteSiteSetting with CLI version: sfdx-cli/7.117.0 win32-x64

### ISSUE THREAD

**Issue by eshettagoyal** [forcedotcom/cli#1189] opened 2021-09-13 15:40 UTC
When we are trying to convert the RemoteSiteSettings from Source format (Sfdx) to mdapi format we are getting an error: Could not infer a metadata type"

Below are the steps to reproduce the issue:
> Created a RemoteSiteSettings named as "BFM" in Salesforce org
> Retrieve it using sfdx force:source:retrieve -m RemoteSiteSetting:BFM
 > Create a folder named as mdApi 
> Run the below command to convert the source-formatted files into the metadata format:
sfdx force:source:convert -d ./mdAPI --json
> Error: "Component conversion failed: C:\\Users\\egoyal\\Downloads\\DeployTo-RMTTEST001_SFPFDI-30403\\DeployTo-RMTTEST001_SFPFDI-30403\\mdAPI\\remoteSiteSettings\\BFM.remoteSit: Could not infer a metadata type"
The issue is replicable only in CLI version: sfdx-cli/7.117.0 win32-x64 node-v14.17.6, however, this works fine with lower versions eg(sfdx-cli/7.110.0 win32-x64 node-v14.17.3).

**Cli configuration:**
sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core) 
@oclif/plugin-help 3.2.2 (core)     
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.8 (core)
auth 1.7.1 (core)
config 1.2.28 (core)
custom-metadata 1.0.12 (core)
data 0.6.1 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.7.0 (core)
salesforce-alm 52.3.2 (core)
schema 1.0.8 (core)
sfdx-cli 7.117.0 (core)
source 1.0.12 (core)
telemetry 1.2.3 (core)
templates 52.1.0 (core)
user 1.4.0 (core)

![image](https://user-images.githubusercontent.com/90635211/133114026-bb7016ed-74c8-4ad9-96c8-5e716ba3d9a4.png)

**Comment by shetzel** [comment] 2021-09-14 16:50
I'm not able to reproduce this with the same version CLI and plugins.  The error message looks like you're converting something downloaded rather than an SDFX project.  That would be the error message you'd see if you tried to source:convert a RemoteSiteSetting in mdapi format.

**Comment by shetzel** [comment] 2021-09-16 21:57
@eshettagoyal 
Can you confirm that this doesn't happen when converting remoteSiteSettings in source format?  If so, please close this.

**Closed as completed** 2021-09-23 22:22 UTC
Labels: more information required
