### ISSUE TITLE
Getting "Error authenticating with the refresh token due to: expired access/refresh token" when running sfdx force:org:shape:list

### ISSUE THREAD

**Issue by eugeneAtGitHub** [forcedotcom/cli#1627] opened 2022-07-13 15:25 UTC
### Summary

Getting "Error authenticating with the refresh token due to: expired access/refresh token" when running sfdx force:org:shape:list if there's any "disconnected" org listed in sfdx force:org:list. 

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Run  sfdx force:org:list and make sure there's org with Connected Status of RefreshTokenAuthError.
1.  Make sure your active org has a connected status
1.  Run sfdx force:org:shape:list 

### Expected result

The sfdx force:org:shape:list command should list all org shapes successfully

### Actual result

ERROR running force:org:shape:list:  Error authenticating with the refresh token due to: expired access/refresh token

### System Information

- Which shell/terminal are you using? bash

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
- {
        "cliVersion": "sfdx-cli/7.157.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-scanner 2.13.2",
                "alias 2.1.0 (core)",
                "apex 0.13.0 (core)",
                "auth 2.2.0 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.6.1 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.157.0 (core)",
                "signups 1.2.0 (core)",
                "source 2.0.3 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.0 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
}
### Additional information

_Feel free to attach a screenshot_.

**Comment by shetzel** [comment] 2022-07-13 18:53
Duplicate of https://github.com/forcedotcom/cli/issues/1615
The fix for this will be in the next sfdx CLI release candidate tomorrow.

**Closed as completed by shetzel** 2022-07-13 18:53 UTC
Labels: investigating
