### ISSUE TITLE
Unexpected error in new version of sfdx package version create command

### ISSUE THREAD

**Issue by bdovh** [forcedotcom/cli#1983] opened 2023-03-06 10:10 UTC
### Summary
We have a script which is creating a package version

sfdx force:package:beta:version:create -d folder --postinstallscript InstallHandler -x -w 60 --codecoverage --json

echo $(cat createPackageVersion.txt)
status=$(cat createPackageVersion.txt | jq '.status' -r )
echo $status
message=$(cat createPackageVersion.txt | jq '.message' -r )

The script read .status and .message properties of the JSON result of the package version create command.
It was working fine on the older version on the SFDX CLI but it now broken

### Steps To Reproduce:

Try to execute a command
$(sfdx force:package:beta:version:create --json)  > createPackageVersion.txt

and then access the message attribute

message=$(cat createPackageVersion.txt | jq '.message' -r )
echo $message

### Expected result

There should be message displayed by the echo command, like it was before

### Actual result

Message is always null in new version of SFDX CLI

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
	
	
Version of SFDX CLI is: sfdx-cli/7.190.2 linux-x64 node-v18.14.2

### Additional information

_Feel free to attach a screenshot_.

**Comment by shetzel** [comment] 2023-11-28 17:30
@bdovh - looks like the message property is there if the command fails, but not there if it's successful.  I'll add a success message back to the JSON response.

**Comment by shetzel** [comment] 2023-11-28 20:03
On second thought, this would make the command inconsistent with the rest of the core commands in the CLI.  Since it's been this way in the packaging plugin for a long time now and you've likely updated your scripts already I'm going to close this as "working as designed".

**Closed as completed by shetzel** 2023-11-28 20:03 UTC
Labels: bug, owned by another team, investigating
