### ISSUE TITLE
Profiles required on HDD when packaging, despite their existence in .forceignore

### ISSUE THREAD

**Issue by triestelaporte** [forcedotcom/cli#341] opened 2020-03-13 16:52 UTC
I had some automatically created profiles surf down into my IDE from a SO, I didn't want these in a package, so very early on in the project I added this to my .forceignore:

```
force-app/main/default/profiles/Admin.profile
force-app/main/default/profiles/Custom%3A Marketing Profile.profile
force-app/main/default/profiles/Custom%3A Sales Profile.profile
force-app/main/default/profiles/Custom%3A Support Profile.profile
force-app/main/default/profiles/authtest Profile.profile
```

I was tired of seeing the files on my hard drive, so this morning I deleted them, knowing they were not packaged anyway.

Verified by examining all existing versions of package, none include the profiles

well, after I cleaned up my drive, I tried to make a new version, and I got this:

> "message": "We couldn't create this package version because new components were added or existing components were deleted. Add components {Profile=[Custom%3A Support Profile, Custom%3A Marketing Profile, Admin, Custom%3A Sales Profile, authtest Profile]} back into the package version, and create the package version again.",

so I went back through my local history and grabbed the profiles, put them back and I ran the exact same command

>  "Status": "Success",

examine package after this, still does not contain profiles, as expected

**Comment by eblazer** [comment] 2023-05-18 22:47
This strategy works through `7.200.4`. It appears that even though these profiles are included in the .forceignore file, they are **still** included in the package.xml sent to Salesforce but not actually packaged.

However starting with `7.200.5`, my builds fail because they are now **not** included in the package.xml sent to Salesforce.

**Comment by shetzel** [comment] 2023-10-04 21:49
I believe this issue is now fixed and is similar to several newer issues such as:
https://github.com/forcedotcom/cli/issues/620
https://github.com/forcedotcom/cli/issues/2336

Profiles are searched within all package directories defined in sfdx-project.json.  .forceignore does not apply in this search, which is by design.  Only aspects of the profiles that are relevant to the metadata being packaged are used.

**Closed as completed by shetzel** 2023-10-04 21:49 UTC
Labels: owned by another team, area:packaging
