### ISSUE TITLE
Uninstalling salesforcedx plug-in doesn't actually uninstall

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/cli#386] opened 2020-05-01 15:31 UTC
### Summary

After uninstalling the salesforcedx plug-in, all the force commands still work and the plug-in is still shown with the --core flag.

### Steps To Reproduce:

1.  Run `sfdx plugins:uninstall salesforcedx`
1.  Receive message that the plug-in is uninstalling
1. Run `sfdx force:apex:class:create -n TestClass`
1. Test class created without issue

### Expected result

Force commands no longer available.

### Actual result

Force commands succeed. Further, running `sfdx plugins --core` shows that the latest version is still installed.

### Additional information

I don't really see this as a bug, but it's unexpected behaviour and I'm curious if it is intentional - removing this plug-in is something I only try if there are problems or I'm on a pre-release and want to upgrade.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
7.56.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
48.12

**OS and version**:
MacOS 10.15.4

**Comment by keirbowden** [comment] 2020-05-01 15:38
I tried downgrading to 46.16.0 and uninstalling that. I got a bunch of messages about it being uninstalled, and when I checked I was back on 48.12. It seems that uninstalling reverts to the latest version of the plug-in that I have locally.

**Comment by shetzel** [comment] 2020-05-01 15:56
You can't uninstall a core plugin, which is by design.  If you don't want the sfdx core plugins then you probably just want the oclif CLI.

If you have a specific version of an sfdx core plugin installed, i.e., not the version bundled with the CLI, then uninstalling will take you back to the plugin version corresponding to the CLI version you have.

I think a potential improvement would be to provide a better message when trying to uninstall a core plugin.  @clairebianchi - any thoughts?

**Comment by xyc** [comment] 2020-08-18 04:43
@shetzel The developer documentation mentions "Uninstall the salesforcedx Plug-In" as well https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm

**Comment by shetzel** [comment] 2020-08-20 14:32
@xyc If you have a non-core version of the salesforcedx plugin you can uninstall it that way.

**Comment by mshanemc** [comment] 2021-05-20 19:05
We're retiring the salesforcedx plugin plugin soon https://github.com/forcedotcom/cli/issues/1016

so I'm closing this.  We have a low-priority WI to tell people they can't uninstall a core plugin (they can uninstall a version of a core plugin that isn't the bundled version, but that just gets them back to the bundled version).

**Closed as completed by mshanemc** 2021-05-20 19:05 UTC
Labels: documentation
