### ISSUE TITLE
force:source:deploy returns "No results found" Due To Changes Of sfdx-project.json

### ISSUE THREAD

**Issue by j-schreiber** [forcedotcom/cli#633] opened 2020-09-23 13:30 UTC
### Summary

- Because 2nd gen packaging [still lacks support for many metadata types](https://mdcoverage.secure.force.com/docs/metadata-coverage), some of my repositories use a dedicated "deploy" folder
- This folder contains source that I need to deploy after the package install, using `force:source:deploy`
- Recent changes in the CLI and how the `sfdx-project.json` works now require the src/deploy folder to be part of the `packageDirectories`. Otherwise, `force:source:deploy` only returns "No results found" (as if the directory was empty)
- However, if I would add the source, this would result the source being included in `force:source:push` and `force:source:pull` commands - which would cause all scripts and pipelines to fail (because metadata like workflow email alerts using org wide email addresses are still incompatible with 2nd gen packaging)

### Steps To Reproduce:

1. Use any repository you have and create a source folder, that is *not* part of sfdx-project.json
2. run `force:source:deploy -p new/source/folder`
3. See, "No results found"-Message
4. Now, add the folder to your sfdx-project.json and run the command again
5. See, that source is deployed

### Expected result

force:source:deploy should not require the directory to be named in the `sfdx-project.json`.

### Actual result

Because force:source:deploy requires the directory in `sfdx-project.json`, I can effectively not maintain "non packaged metadata" in source format in my repositories and deploy it.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.74.1-32db2396ed darwin-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.10.0 (core)
├─ templates 49.4.4 (core)
├─ custom-metadata 1.0.10 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 49.11.0 (core)
└─ apex 0.0.9 (core)
sfdx-cli 7.74.1 (core)
texei-sfdx-plugin 1.7.0

**OS and version**:
Mac

**Comment by shetzel** [comment] 2020-09-23 14:57
Thank you for the detailed bug report.  This fix is queued for the next patch release and a dupe of #622

**Closed as completed by shetzel** 2020-09-23 14:57 UTC
