### ISSUE TITLE
sfdx ignoring restDeploy config

### ISSUE THREAD

**Issue by rlbarreto** [forcedotcom/cli#1616] opened 2022-07-08 09:56 UTC
### Summary

When executin `sfdx force:source:push -f` it is always using SOAP 

### Steps To Reproduce:

1. execute `sfdx config:set restDeploy=true`
1. execute `sfdx force:source:push -f`

### Expected result

Should show message "Pushing with REST API v54"

### Actual result

Shows message "Pushing with SOAP API v54.0" and then it fails with max request size(my project)

### System Information

- Which shell/terminal are you using? zsh

{
        "cliVersion": "sfdx-cli/7.158.1",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
                "alias 2.1.0 (core)",
                "apex 0.13.0 (core)",
                "auth 2.2.2 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "functions 1.8.0",
                "generator 2.0.2 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 2.0.1 (core)",
                "salesforce-alm 54.6.2 (core)",
                "schema 2.1.1 (core)",
                "sfdmu 4.15.0",
                "sfdx-cli 7.158.1 (core)",
                "sfdx-wry-plugin 0.0.11",
                "signups 1.2.0 (core)",
                "source 2.0.3 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.1 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Darwin 21.5.0"
}

**Comment by rlbarreto** [comment] 2022-07-08 09:56
I have tried to use `sfdx config:set restDeploy=true --global` and got the same situation

**Comment by maggiben** [comment] 2022-07-08 14:04
Hello, can you please try setting env var `SFDX_REST_DEPLOY` to true ?

**Comment by rlbarreto** [comment] 2022-07-08 15:01
I have tried and got the same result. I have the evironment variable and the config set to use REST, but it's not working.

Em sex., 8 de jul. de 2022 às 15:04, Benjamin ***@***.***>
escreveu:

**Comment by maggiben** [comment] 2022-07-12 13:42
Hello, I would like to check the org setting, can you provide an org to repro ?

**Comment by mshanemc** [comment] 2022-07-13 15:54
this is a bug fixed by https://github.com/salesforcecli/plugin-source/pull/535 @W-11390183@

**Comment by mshanemc** [comment] 2022-07-13 15:54
duplicate of https://github.com/forcedotcom/cli/issues/1606

**Closed as completed** 2022-07-21 17:14 UTC
Labels: more information required, investigating
