### ISSUE TITLE
Regression: Audience metadata type not supported anymore in 7.65.3-74dd02e949

### ISSUE THREAD

**Issue by dobias** [forcedotcom/cli#476] opened 2020-07-13 09:11 UTC
### Summary

Today we are facing some difficulties with the new sfdx tooling 7.65.3-74dd02e949
When i.e. refreshing an Audience file (which still works perfectly in 7.62.1-309fe6da17), the following errror is raised:

`
SfdxError
			We canâ€™t retrieve the specified metadata object: Audience. Certain metadata types, like Audience are not currently supported by the CLI.
			File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
`

### Steps To Reproduce:

See above

### Expected result

sfdx should still have retrieved the org metadata for the selected Audience file, as it did with previous versions.

### Actual result

Error: Certain metadata types, like Audience are not currently supported by the CLI

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.65.3-74dd02e949 win32-x64 node-v10.21.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
7.65.3
**OS and version**:
Windows 10

**Comment by kylethornton** [comment] 2020-07-13 14:03
We are seeing the same but the error is `Unexpected file found in package directory:` for an audience. These have been working for months. 

Same SFDX CLI version and sfdx version, OS is linux on Travis

**Comment by dobias** [comment] 2020-07-13 15:35
@kylethornton We have this problem too - see IC2 screenshot below when trying to deploy stuff via their SFDX integration:
![image](https://user-images.githubusercontent.com/2144760/87323527-3154d780-c52f-11ea-84ae-e3cabdcd6931.png)

**Comment by rvwatch** [comment] 2020-07-13 16:24
This type is on our radar and the internal team that owns the Audience type has been notified of the issue. They will be working to get this type included but there's not specific eta on that just yet, unfortuntately. In the meantime, you can use force:mdapi:retrieve, but please be aware you won’t have access to the benefits of source tracking with mdapi commands. Apologies for the inconvenience and we'll update you on the Audience type soon.

**Comment by kylethornton** [comment] 2020-07-13 16:46
The issue is that this all worked before and as of the latest update deployments are now blowing up.

**Comment by amphro** [comment] 2020-07-15 16:27
Duplicate of #470

**Closed as completed by amphro** 2020-07-15 16:27 UTC
Labels: duplicate
