### ISSUE TITLE
Unidentified metadata error - SharingGuestRule

### ISSUE THREAD

**Issue by IVerkhosh** [forcedotcom/cli#1170] opened 2021-09-05 07:50 UTC
### Summary

Getting error retrieving from org, when "SharingGuestRule" included in the package.xml

### Steps To Reproduce:
1. In package.xml, include SharingGuestRule metadata
       <types>
		<members>Customer_Information__c.Guest_User</members>
		<name>SharingGuestRule</name>
	</types> 
2. Execute sfdx force:source:retrieve -x ./manifest/package.xml

### Expected result
All metadata in the package.xml file retrieved

### Actual result
Unidentified metadata error - SharingGuestRule

### System Information
{
"cliVersion": "sfdx-cli/7.116.2",
"architecture": "win32-x64",
"nodeVersion": "node-v14.17.5",
"pluginVersions": [
"@oclif/plugin-autocomplete 0.3.0 (core)",
"@oclif/plugin-commands 1.3.0 (core)",
"@oclif/plugin-help 3.2.2 (core)",
"@oclif/plugin-not-found 1.2.4 (core)",
"@oclif/plugin-plugins 1.10.1 (core)",
"@oclif/plugin-update 1.4.0-3 (core)",
"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
"@oclif/plugin-which 1.0.3 (core)",
"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
"@salesforce/sfdx-trust 3.6.0 (core)",
"alias 1.1.10 (core)",
"apex 0.2.8 (core)",
"auth 1.7.1 (core)",
"config 1.2.24 (core)",
"custom-metadata 1.0.12 (core)",
"data 0.6.1 (core)",
"generator 1.1.7 (core)",
"limits 1.2.1 (core)",
"org 1.7.0 (core)",
"salesforce-alm 52.3.1 (core)",
"schema 1.0.8 (core)",
"sfdx-cli 7.116.2 (core)",
"source 1.0.12 (core)",
"telemetry 1.2.3 (core)",
"templates 52.1.0 (core)",
"user 1.4.0 (core)"
],
"osVersion": "Windows_NT 10.0.18363"
}

### Additional information
sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.8 (core)
auth 1.7.1 (core)
config 1.2.24 (core)
custom-metadata 1.0.12 (core)
data 0.6.1 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.7.0 (core)
salesforce-alm 52.3.1 (core)
schema 1.0.8 (core)
sfdx-cli 7.116.2 (core)
source 1.0.12 (core)
telemetry 1.2.3 (core)
templates 52.1.0 (core)
user 1.4.0 (core)

**Comment by mshanemc** [comment] 2021-09-10 13:53
this should be fixed in 7.118.1 (currently tagged as latest-rc).

**Comment by mshanemc** [comment] 2021-09-27 15:14
duplicate of https://github.com/forcedotcom/cli/issues/1199

**Closed as completed by mshanemc** 2021-09-27 15:14 UTC
Labels: duplicate, investigating
