### ISSUE TITLE
Pushing customised duplicate and matching rules causes an error.

### ISSUE THREAD

**Issue by DT-Forcology** [forcedotcom/cli#569] opened 2020-08-19 17:52 UTC
### Summary

When deploying customised duplicate and matching rules using force:source:push, the duplicate rule fails to deploy. This occurs if both the duplicate rule and the corresponding (new) matching rules are also active.

### Steps To Reproduce:

Create a new scratch org.

Add a new matching rule for account. Select any field for matching. Activate the matching rule
Add this new matching rule to the standard account duplicate rule.
Run force:source:pull

Create another scratch org.
Run force:source:push in to the new scratch org

### Expected result

Deployment occurs successfully

### Actual result

Deployment fails with the following error: Before you can use this duplicate rule, all associated matching rules must be active and have their fields mapped

### Additional Information

Deploying the duplicate rule as inactive and then activating it does work. We want to use a scratch org for CI, so this doesn't work for us.

I assume this bug is due to matching rules taking time to activate

**Comment by clairebianchi** [comment] 2020-10-23 17:59
Duplicate of #685

**Closed as completed by clairebianchi** 2020-10-23 17:59 UTC
