### ISSUE TITLE
Too Many Files Error

### ISSUE THREAD

**Issue by MGarfOppLoans** [forcedotcom/cli#449] opened 2020-06-18 20:44 UTC
### Summary

EMFILE: too many open files

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

Run  sfdx force:lightning:lwc:start

### Actual result

unhandledPromiseRejection: Error: EMFILE: too many open files, open 'C:\Users\*******\AppData\Local\sfdx\node_modules\negotiator\lib\language.js'

### Additional information

_Feel free to attach a screenshot_.

Please use https://github.com/isaacs/node-graceful-fs. Its designed for this.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

Latest

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

Latest

**OS and version**:

Windows 10

**Comment by JonnyPower** [comment] 2020-08-10 17:37
+1 - seeing the same

```
[SL-JPOWER] jpower traction-pay-2-sfdc $ sfdx force:source:push -u test-bhfzuubkichf@example.com
(node:16099) Warning: The query result is missing 10000 records due to a 10,000 limit for performance reasons. Increase the number of records returned by setting the config value "maxQueryLimit" or the environment variable "SFDX_MAX_QUERY_LIMIT" to 10000 or greater than 10,000.
(node:16099) Warning: The query result is missing 10000 records due to a 10,000 limit for performance reasons. Increase the number of records returned by setting the config value "maxQueryLimit" or the environment variable "SFDX_MAX_QUERY_LIMIT" to 10000 or greater than 10,000.
Error: EMFILE: too many open files, open '/usr/local/lib/sfdx/node_modules/lazystream/lib/lazystream.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Module._load (internal/modules/cjs/loader.js:878:14)
    at LazyLoader.loadIfNeeded (/usr/local/lib/sfdx/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:63:19)
    at Object.get (/usr/local/lib/sfdx/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:219:28)
    at Proxy.utils.lazyReadStream (/usr/local/lib/sfdx/node_modules/archiver-utils/index.js:78:25)
    at Archiver._updateQueueTaskWithStats (/usr/local/lib/sfdx/node_modules/archiver/lib/core.js:438:24)
    at Archiver._append (/usr/local/lib/sfdx/node_modules/archiver/lib/core.js:105:17)
    at /usr/local/lib/sfdx/node_modules/archiver/lib/core.js:663:14
    at Array.forEach (<anonymous>)
    at /usr/local/lib/sfdx/node_modules/archiver/lib/core.js:644:15
    at next (/usr/local/lib/sfdx/node_modules/archiver-utils/index.js:131:16)
    at /usr/local/lib/sfdx/node_modules/archiver-utils/index.js:151:11
    at callback (/usr/local/lib/sfdx/node_modules/graceful-fs/polyfills.js:295:20) {
  errno: -24,
  syscall: 'open',
  code: 'EMFILE',
  path: '/usr/local/lib/sfdx/node_modules/lazystream/lib/lazystream.js'
}
Error: EMFILE: too many open files, open '/usr/local/lib/sfdx/node_modules/lazystream/lib/lazystream.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Module._load (internal/modules/cjs/loader.js:878:14)
    at LazyLoader.loadIfNeeded (/usr/local/lib/sfdx/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:63:19)
    at Object.get (/usr/local/lib/sfdx/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:219:28)
    at Proxy.utils.lazyReadStream (/usr/local/lib/sfdx/node_modules/archiver-utils/index.js:78:25)
    at Archiver._updateQueueTaskWithStats (/usr/local/lib/sfdx/node_modules/archiver/lib/core.js:438:24)
    at Archiver._append (/usr/local/lib/sfdx/node_modules/archiver/lib/core.js:105:17)
    at /usr/local/lib/sfdx/node_modules/archiver/lib/core.js:663:14
    at Array.forEach (<anonymous>)
    at /usr/local/lib/sfdx/node_modules/archiver/lib/core.js:644:15
    at next (/usr/local/lib/sfdx/node_modules/archiver-utils/index.js:131:16)
    at /usr/local/lib/sfdx/node_modules/archiver-utils/index.js:151:11
    at callback (/usr/local/lib/sfdx/node_modules/graceful-fs/polyfills.js:295:20) {
  errno: -24,
  syscall: 'open',
  code: 'EMFILE',
  path: '/usr/local/lib/sfdx/node_modules/lazystream/lib/lazystream.js'
}
Error: EMFILE: too many open files, open '/usr/local/lib/sfdx/node_modules/lazystream/lib/lazystream.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Module._load (internal/modules/cjs/loader.js:878:14)
    at LazyLoader.loadIfNeeded (/usr/local/lib/sfdx/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:63:19)
    at Object.get (/usr/local/lib/sfdx/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:219:28)
    at Proxy.utils.lazyReadStream (/usr/local/lib/sfdx/node_modules/archiver-utils/index.js:78:25)
    at Archiver._updateQueueTaskWithStats (/usr/local/lib/sfdx/node_modules/archiver/lib/core.js:438:24)
    at Archiver._append (/usr/local/lib/sfdx/node_modules/archiver/lib/core.js:105:17)
    at /usr/local/lib/sfdx/node_modules/archiver/lib/core.js:663:14
    at Array.forEach (<anonymous>)
    at /usr/local/lib/sfdx/node_modules/archiver/lib/core.js:644:15
    at next (/usr/local/lib/sfdx/node_modules/archiver-utils/index.js:131:16)
    at /usr/local/lib/sfdx/node_modules/archiver-utils/index.js:151:11
    at callback (/usr/local/lib/sfdx/node_modules/graceful-fs/polyfills.js:295:20) {
  errno: -24,
  syscall: 'open',
  code: 'EMFILE',
  path: '/usr/local/lib/sfdx/node_modules/lazystream/lib/lazystream.js'
}
```

That's after raising my open file limit too;

```
[SL-JPOWER] jpower traction-pay-2-sfdc $ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 50877
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 2048
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 50877
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by clairebianchi** [comment] 2020-08-25 18:20
This is a duplicate of this https://github.com/forcedotcom/cli/issues/487 issue, which we actively working to fix

**Closed as completed by clairebianchi** 2020-08-25 18:20 UTC
Labels: duplicate
