### ISSUE TITLE
`sf autocomplete` instructions failing for fish shell

### ISSUE THREAD

**Issue by jmssmth** [forcedotcom/cli#2658] opened 2024-01-19 17:58 UTC
### Summary
`sf autocomplete` instructions failing for fish shell

### Steps To Reproduce
using fish shell on a macos 14.2.1 (silicon), successfully installed latest sf platform binary (2.24.4). `sf autocomplete` output states:
> 1) Add the autocomplete env var to your fish profile and source it...
> $ printf "eval $(sf autocomplete script fish)" >> ~/.fishrc; source ~/.fishrc

### Expected result
not sure, first time updating to sf v2 so not sure what success for this command looks like

### Actual result
The `sf autocomplete` fails producing this output:
> › Error: Expected fish to be one of: zsh, bash, powershell
> › See more help with --help

Sidenote: why instruct the use of a fish config file (`.fishrc`) that isn't even in the [fish configuration](https://fishshell.com/docs/current/language.html#configuration) documentation? It should be `config.fish` instead. 

### System Information
fish shell version 3.7.0

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.24.4",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Darwin 23.2.0",
  "rootPath": "/usr/local/lib/sf",
  "shell": "fish",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.0 (core)",
    "@oclif/plugin-help 6.0.10 (core)",
    "@oclif/plugin-not-found 3.0.8 (core)",
    "@oclif/plugin-plugins 4.1.15 (core)",
    "@oclif/plugin-search 1.0.11 (core)",
    "@oclif/plugin-update 4.1.7 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.14 (core)",
    "@salesforce/cli 2.24.4 (core)",
    "apex 3.0.17 (core)",
    "auth 3.2.0 (core)",
    "data 3.0.14 (core)",
    "deploy-retrieve 3.1.0 (core)",
    "info 3.0.15 (core)",
    "limits 3.1.2 (core)",
    "marketplace 1.0.16 (core)",
    "org 3.2.2 (core)",
    "packaging 2.1.0 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.15 (core)",
    "sobject 1.1.0 (core)",
    "source 3.1.3 (core)",
    "telemetry 3.1.9 (core)",
    "templates 56.0.9 (core)",
    "trust 3.3.1 (core)",
    "user 3.2.1 (core)"
  ]
}
```

**Comment by shetzel** [comment] 2024-01-19 18:50
This is a duplicate of https://github.com/oclif/plugin-autocomplete/issues/3
Also see: https://github.com/oclif/plugin-autocomplete/pull/175

There's no support yet.  Feel free to contribute to the conversation there and/or the PR.

**Closed as completed by shetzel** 2024-01-19 18:50 UTC
Labels: investigating, validated
