### ISSUE TITLE
Unable to retrieve Audience

### ISSUE THREAD

**Issue by mpdeglau** [forcedotcom/cli#237] opened 2019-11-14 16:44 UTC
### Summary

When trying to retrieve Audiences from a scratch org using `sfdx force:source:retrieve -m Audience` I get the error 'Cannot read property 'metadataName' of undefined'.

### Steps To Reproduce:

1.  Create an audience in a scratch org.
1.  Pull the changes down using `sfdx force:source:retrieve -m Audience`

### Expected result

The Audience metadata is pulled down into the audiences directory.

### Actual result

This is the error returned
```
ERROR running force:source:retrieve:  Cannot read property 'metadataName' of undefined
```
Attached is the output with debug mode enabled.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.32.0 darwin-x64 node-v10.15.3
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.2.2 (core)
generator 1.1.2 (core)
salesforcedx 47.5.0 (core)
├─ salesforcedx-templates 47.5.0 (core)
└─ salesforce-alm 47.8.0 (core)

sfdx-cli 7.32.0 (core)
**OS and version**:
Mac 10.14
[debuglog.txt](https://github.com/forcedotcom/cli/files/3847609/debuglog.txt)

**Comment by clairebianchi** [comment] 2019-11-15 20:59
@mpdeglau this is a duplicate of https://github.com/forcedotcom/cli/issues/151. I am closing this one

**Closed as completed by clairebianchi** 2019-11-15 20:59 UTC
Labels: bug
