### ISSUE TITLE
ERROR running force:source:deploy:  The PermissionSet named ContentHubUser was not found in the workspace.

### ISSUE THREAD

**Issue by shivani-ar** [forcedotcom/cli#851] opened 2021-02-16 14:27 UTC
### Summary

sfdx force:source:deploy -p "force-app/main/default/permissionsets/BDR_Extra_Access.permissionset-meta.xml" 
ERROR running force:source:deploy:  The PermissionSet named BDR_Extra_Acces was not found in the workspace.

### Steps To Reproduce:

1. Checkout to a branch to deploy permission set to sandbox or scratch org
2. Try to deploy any permission set with below commands 
   sfdx force:source:deploy -p "force-app/main/default/permissionsets/BDR_Extra_Access.permissionset-meta.xml" 
   sfdx force:source:deploy -p "force-app\main\default\permissionsets\BDR_Extra_Access.permissionset-meta.xml"  
   sfdx force:source:deploy -p  force-app/main/default/permissionsets/BDR_Extra_Access.permissionset-meta.xml 

### Expected result

It should deploy specified Permission Set in specified org (Sandbox/ Scratch org)

### Actual result
ERROR running force:source:deploy:  The PermissionSet named BDR_Extra_Access was not found in the workspace.

### Additional information

**SFDX CLI Version**
sfdx-cli/7.85.1-2fb9e41053 win32-x64 node-v12.18.3

**SFDX plugin Version**
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 51.0.2 (latest-rc)
├─ user 1.1.0
├─ salesforce-alm 51.0.1
├─ limits 1.0.3
├─ schema 1.0.3
├─ apex 0.1.4
├─ templates 51.1.0
├─ custom-metadata 1.0.11
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7
sfdx-cli 7.85.1 (core)
sfpowerkit 2.6.5
shane-sfdx-plugins 4.43.0
├─ @mshanemc/plugin-streaming 1.1.7
└─ @mshanemc/sfdx-sosl 1.1.0

**OS and version**:
Windows 10 Pro

**Comment by mshanemc** [comment] 2021-02-16 14:39
Your command is using `BDR_Extra_Access` and it's trying to deploy `BDR_Extra_Acces` (missing an `s`)

Can you look through all the filenames in your source and make sure they're spelled correctly, including the `label` property?

**Comment by shivani-ar** [comment] 2021-02-16 15:06
@mshanemc sorry! That was typo. Yes all name and labels are correct.

**Comment by chernyy-svyat** [comment] 2021-02-17 19:48
@shivani-ar this error can be caused by the presence of `BDR_Extra_Access` in the `.forceignore` file. Check it.

**Comment by shivani-ar** [comment] 2021-02-17 20:10
No its not in .forceignore file and its not working for any permission set.

**Comment by mdonnalley** [comment] 2021-02-18 15:59
@shivani-ar @dpuza-formativ try downgrading salesforcedx to 50.16.1

```
sfdx plugins:install salesforcedx@50.16.1
```

I'll continue investigating what's going on but downgrading should unblock you in the meantime

**Comment by mdonnalley** [comment] 2021-03-09 21:05
Closing this because we reverted the failing code in `salesforcedx@51.1.0`

**Closed as completed by mdonnalley** 2021-03-09 21:05 UTC
Labels: bug, investigating
