### ISSUE TITLE
The new sfdx-cli/7.66.2 version is breaking deployment

### ISSUE THREAD

**Issue by Gaurav-Trivedi** [forcedotcom/cli#506] opened 2020-07-21 19:57 UTC
### Summary

With this new release of sfdx-cli/7.66.2 and we try to deploy any component it throws an error UnexpectedFileFound

### Steps To Reproduce:

1.  In the project directory, we have `audience` metadata (folder)
1.  try to deploy any component ApexClass, CustomField, etc.
1.  use sfdx deploy command to deploy any component using package.xml
1.  you will receive an error `UnexpectedFileFound: Unexpected file found in package directory: /force-app/main/default/audience/Default_Client Intake.audience-meta.xml`

### Expected result

It should deploy the changes we have in package.xml

### Actual result
`UnexpectedFileFound: Unexpected file found in package directory: /force-app/main/default/audience/Default_Client Intake.audience-meta.xml`

**Comment by shetzel** [comment] 2020-07-21 20:13
Duplicate of #470

**Closed as completed by shetzel** 2020-07-21 20:13 UTC
