### ISSUE TITLE
Regression: Audiences no longer retrievable in 7.65.3 and 7.65.4

### ISSUE THREAD

**Issue by kidjansen** [forcedotcom/cli#483] opened 2020-07-15 08:14 UTC
### Summary

Retrieval of Audiences no longer works in 7.65.3 and 7.65.4, results in following error message:

_We can't retrieve the specified metadata object: Audience. Certain metadata types, like Audience are not currently supported by the CLI._

In 7.64.x and earlier retrieval of Audiences did work without issues on the same org.

### Steps To Reproduce:

Can't share repo (customer IP), but you can contact me if needed for screen sharing session (CET/CEST time zone).

1.  sfdx force:source:retrieve on a sandbox or production org (probably also scratch orgs, but not tested) that has Audiences with the at least one Audience in the retrieval scope.

### Expected result

retrieval of the audiences in the retrieval scope (package.xml)

### Actual result

error: _We can't retrieve the specified metadata object: Audience. Certain metadata types, like Audience are not currently supported by the CLI._

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
applicable to both 7.65.3 and 7.65.4, did work in 7.64.x and earlier.

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 48.22.8 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ custom-metadata 1.0.4 (core)
└─ salesforce-alm 48.24.1 (core)
sfdx-cli 7.65.4 (core)

**OS and version**:
Windows 10 Pro with all updates

**Comment by amphro** [comment] 2020-07-15 16:27
Duplicate of #470

**Closed as completed by amphro** 2020-07-15 16:27 UTC
Labels: duplicate
