### ISSUE TITLE
sf project retrieve start is requesting "directory with a valid DX project" even when using METADATA API FORMAT FLAGS

### ISSUE THREAD

**Issue by yurifugi** [forcedotcom/cli#2831] opened 2024-04-18 19:01 UTC
Using the latest sf version
```
❯ sf -v
@salesforce/cli/2.36.8 linux-x64 node-v20.11.1
```

After issuing the retrieve command,  with parameters indicating that the retrieve is for a .zip file containing metadata API format:

```
sf project retrieve start  \
    --zip-file-name -unpackaged.zip \
    --json \
    --target-metadata-dir . \
    --wait 300 \
    --manifest package.xml \
    --target-org org-prod

```

the command will return with an error message stating that the command must be run from inside a sfdx project:

```
{
  "code": 1,
  "context": "RetrieveMetadata",
  "commandName": "RetrieveMetadata",
  "message": "This directory does not contain a valid Salesforce DX project.",
  "name": "InvalidProjectWorkspaceError",
  "status": 1,
  "stack": "InvalidProjectWorkspaceError: This directory does not contain a valid Salesforce DX project.\n    at Messages.createError (/home/yuri/.local/share/sf/client/2.36.8-fa01960/node_modules/@salesforce/core/lib/messages.js:431:16)\n    at resolveProjectPathSync (/home/yuri/.local/share/sf/client/2.36.8-fa01960/node_modules/@salesforce/core/lib/util/internal.js:80:24)\n    at SfProject.resolveProjectPathSync (/home/yuri/.local/share/sf/client/2.36.8-fa01960/node_modules/@salesforce/core/lib/sfProject.js:393:54)\n    at SfProject.getInstance (/home/yuri/.local/share/sf/client/2.36.8-fa01960/node_modules/@salesforce/core/lib/sfProject.js:360:21)\n    at RetrieveMetadata.run (file:///home/yuri/.local/share/sf/client/2.36.8-fa01960/node_modules/@salesforce/plugin-deploy-retrieve/lib/commands/project/retrieve/start.js:139:68)\n    at async RetrieveMetadata._run (/home/yuri/.local/share/sf/client/2.36.8-fa01960/node_modules/@oclif/core/lib/command.js:311:22)\n    at async Config.runCommand (/home/yuri/.local/share/sf/client/2.36.8-fa01960/node_modules/@oclif/core/lib/config/config.js:433:25)\n    at async run (/home/yuri/.local/share/sf/client/2.36.8-fa01960/node_modules/@oclif/core/lib/main.js:92:16)",
  "exitCode": 1,
  "warnings": []
}
```
For earlier sf versions the retrieve in metadata API format was possible without running the command inside a sfdx directory folder.

Is this the expected behavior now? Or should it still be possible to retieve metadata API format inside a regular directory?

**Comment by yurifugi** [comment] 2024-04-18 19:18
```
❯ sf version --verbose --json
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.36.8",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Linux 5.14.21-150400.24.100-default",
  "rootPath": "/home/yuri/.local/share/sf/client/2.36.8-fa01960",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.2 (core)",
    "@oclif/plugin-help 6.0.20 (core)",
    "@oclif/plugin-not-found 3.1.1 (core)",
    "@oclif/plugin-plugins 5.0.5 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.3 (core)",
    "@oclif/plugin-version 2.0.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.7 (core)",
    "@salesforce/cli 2.36.8 (core)",
    "apex 3.1.3 (core)",
    "auth 3.5.1 (core)",
    "data 3.2.4 (core)",
    "deploy-retrieve 3.5.3 (core)",
    "info 3.1.2 (core)",
    "limits 3.2.1 (core)",
    "marketplace 1.1.0 (core)",
    "org 3.6.3 (core)",
    "packaging 2.3.0 (core)",
    "schema 3.2.0 (core)",
    "settings 2.1.2 (core)",
    "sobject 1.2.1 (core)",
    "source 3.2.2 (core)",
    "telemetry 3.1.17 (core)",
    "templates 56.1.0 (core)",
    "trust 3.5.1 (core)",
    "user 3.4.3 (core)"
  ]
}

```

**Comment by yurifugi** [comment] 2024-04-18 19:24
Hello,

I have update `sf` to the lastest version:

```
❯ sf version --verbose --json
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.37.4",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Linux 5.14.21-150400.24.100-default",
  "rootPath": "/home/yuri/.local/share/sf/client/2.37.4-fb2a8ae",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.2 (core)",
    "@oclif/plugin-help 6.0.20 (core)",
    "@oclif/plugin-not-found 3.1.2 (core)",
    "@oclif/plugin-plugins 5.0.7 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.4 (core)",
    "@oclif/plugin-version 2.0.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.7 (core)",
    "@salesforce/cli 2.37.4 (core)",
    "apex 3.1.4 (core)",
    "auth 3.5.5 (core)",
    "data 3.2.5 (core)",
    "deploy-retrieve 3.5.6 (core)",
    "info 3.1.3 (core)",
    "limits 3.2.1 (core)",
    "marketplace 1.1.1 (core)",
    "org 4.0.4 (core)",
    "packaging 2.3.0 (core)",
    "schema 3.2.1 (core)",
    "settings 2.1.2 (core)",
    "sobject 1.2.2 (core)",
    "source 3.2.3 (core)",
    "telemetry 3.1.18 (core)",
    "templates 56.1.1 (core)",
    "trust 3.5.4 (core)",
    "user 3.4.3 (core)"
  ]
}

```

After updating `sf`, the retrieve command continues returning with error because it was issued not on a sfdx project directory:

```
❯ sf project retrieve start  --zip-file-name unpackaged.zip --json --target-metadata-dir . --wait 300 --manifest package.xml --target-org org-prod
{
  "code": 1,
  "context": "RetrieveMetadata",
  "commandName": "RetrieveMetadata",
  "message": "This directory does not contain a valid Salesforce DX project.",
  "name": "InvalidProjectWorkspaceError",
  "status": 1,
  "stack": "InvalidProjectWorkspaceError: This directory does not contain a valid Salesforce DX project.\n    at Messages.createError (/home/yuri/.local/share/sf/client/2.37.4-fb2a8ae/node_modules/@salesforce/core/lib/messages.js:431:16)\n    at resolveProjectPathSync (/home/yuri/.local/share/sf/client/2.37.4-fb2a8ae/node_modules/@salesforce/core/lib/util/internal.js:80:24)\n    at SfProject.resolveProjectPathSync (/home/yuri/.local/share/sf/client/2.37.4-fb2a8ae/node_modules/@salesforce/core/lib/sfProject.js:393:54)\n    at SfProject.getInstance (/home/yuri/.local/share/sf/client/2.37.4-fb2a8ae/node_modules/@salesforce/core/lib/sfProject.js:360:21)\n    at RetrieveMetadata.run (file:///home/yuri/.local/share/sf/client/2.37.4-fb2a8ae/node_modules/@salesforce/plugin-deploy-retrieve/lib/commands/project/retrieve/start.js:139:68)\n    at async RetrieveMetadata._run (/home/yuri/.local/share/sf/client/2.37.4-fb2a8ae/node_modules/@oclif/core/lib/command.js:311:22)\n    at async Config.runCommand (/home/yuri/.local/share/sf/client/2.37.4-fb2a8ae/node_modules/@oclif/core/lib/config/config.js:433:25)\n    at async run (/home/yuri/.local/share/sf/client/2.37.4-fb2a8ae/node_modules/@oclif/core/lib/main.js:92:16)",
  "exitCode": 1,
  "warnings": []
}

```

**Comment by jhgihub0** [comment] 2024-04-19 14:40
I have the same issue https://github.com/forcedotcom/cli/issues/2832.  It seems it started with 2.36.2

**Comment by mshanemc** [comment] 2024-04-19 15:43
duplicate of #2832  (I know this was one was in a couple hours earlier, but I saw the other one first)

**Comment by mshanemc** [comment] 2024-04-19 15:43
found the bug, have a fix coming

**Closed as completed by mshanemc** 2024-04-19 15:43 UTC
Labels: investigating, validated

**Comment by jhgihub0** [comment] 2024-04-22 15:30
2.39.4 fixed for me
