### ISSUE TITLE
The DuplicateRule named Lead.Standard_Rule_for_Leads_with_Duplicate_Contacts was not found in the workspace.

### ISSUE THREAD

**Issue by julycm92** [forcedotcom/cli#728] opened 2020-11-05 17:56 UTC
### Summary

I am trying to deploy a Duplicated Rule that is in my workspace but, I am getting this message:

**The DuplicateRule named Lead.Standard_Rule_for_Leads_with_Duplicate_Contacts was not found in the workspace.**

### Steps To Reproduce:

Deploy a duplicated rule for instance:

1.  **sfdx force:source:deploy  -p force-app/main/default/duplicateRules/Lead.Alerta_de_candidatos_duplicados.duplicateRule-meta.xml**

This is happening with every duplicated rule in my project.

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/7074030/98278178-fdd30880-1f76-11eb-81d5-954ef8455969.png)
![image](https://user-images.githubusercontent.com/7074030/98278202-0592ad00-1f77-11eb-97a3-7273e2696151.png)

**SFDX CLI Version**
sfdx-cli/7.78.1-5a65d9dd2f darwin-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.1.10 (core)
generator 1.1.3 (core)
salesforcedx 50.3.1 (core)
├─ salesforce-alm 50.3.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
├─ templates 50.1.0 (core)
└─ apex 0.1.2 (core)
sfdx-cli 7.78.1 (core)
sfpowerkit 2.2.5 (2.2.5)

**OS and version**:
MAC OS: 10.15.7 (19H2)

**Comment by shetzel** [comment] 2020-11-05 20:29
Duplicate of #685  Please see that issue for workarounds.  The fix will be in an upcoming patch release.

**Closed as completed by shetzel** 2020-11-05 20:29 UTC

**Comment by julycm92** [comment] 2020-11-06 18:51
Thank you for your support @shetzel
