### ISSUE TITLE
`sf package version create` fails without an error, log, or `Package2VersionCreateRequest` being created

### ISSUE THREAD

**Issue by the-last-byte** [forcedotcom/cli#2469] opened 2023-09-14 11:16 UTC
Hi!

I've created an unlocked package, published 5 versions incrementally adding items.

The following command was used to create the package (no issues there):
```ps
sf package version create --package "SomePackage" --installation-key "SomeKey" --target-hub-org SomeDevHub --code-coverage
```

The command to create the versions (where it is failing without error):
```ps
sf package version create --package "SomePackage" --installation-key "SomeKey" --target-hub-org SomeDevHub --verbose --wait 10
```

![2023-09-14_21-04-11](https://github.com/forcedotcom/cli/assets/33075738/11116da0-9501-4816-bb6d-9f3a7039c9db)

No logs are being generated under `%APPDATA%\Local\sf\error.log` or under `%USERPROFILE%\.sf\*`.  Logs are being updated - just the `sf package version create` isn't generating anything.  Additionally, no `Package2VersionCreateRequest` is being created - just the request stops without error.  Sometimes it says done - but no error.

No issues deploying the following:
* `ApexClass` (81 including the ~24 that are generated when an 'experience' is spun up)
* `ApexComponent` (only the standard `SiteFooter`, `SiteHeader`, `SiteLogin`, and `SitePoweredBy`).
* `ApexTrigger` (x 4)
* `AuraDefinitionBundle` (x9)
* `CompactLayout` (x6 inc 2 standard)
* `ContentAsset` (x3)
* `CustomApplication` (x1)
* `CustomField` (x67 including some standards)
* `CustomLabel` (x4)
* `CustomObject` (x8 inc 2 standard)
* `CustomTab` (x7 inc 2 standard)
* `DuplicateRule` (x1)
* `FlexiPage` (x4)
* `GlobalValueSet` (x3)
* `Layout` (x13 inc 2 standard)
* `LightningComponentBundle` (x35)
* `ListView` (x11)
* `MatchingRule` (x1)
* `RecordType` (x12)
* `StaticResource` (x4 inc 2 standard site generated)

All of these metadata types have appeared to work.

If I add the standard pages to the package it fails without error:
```xml
    <types>
        <members>AnswersHome</members>
        <members>BandwidthExceeded</members>
        <members>ChangePassword</members>
        <members>CommunitiesLanding</members>
        <members>CommunitiesLogin</members>
        <members>CommunitiesSelfReg</members>
        <members>CommunitiesSelfRegConfirm</members>
        <members>CommunitiesTemplate</members>
        <members>Exception</members>
        <members>FileNotFound</members>
        <members>ForgotPassword</members>
        <members>ForgotPasswordConfirm</members>
        <members>IdeasHome</members>
        <members>InMaintenance</members>
        <members>MicrobatchSelfReg</members>
        <members>MyProfilePage</members>
        <members>NonEssentialsMobileLanding</members>
        <members>SiteLogin</members>
        <members>SiteRegister</members>
        <members>SiteRegisterConfirm</members>
        <members>SiteTemplate</members>
        <members>StdExceptionTemplate</members>
        <members>Unauthorized</members>
        <members>UnderConstruction</members>
        <name>ApexPage</name>
    </types>
```
I managed after a few variations of the above and managed to get `AnswersHome`, `BandwidthExceeded`, `ChangePassword`, and some of the `Communities*` pages in - but it seems to fail - even if the pages are empty.  I tried adding a custom page with no contents and it also fails.

It also failed in the same way after just adding all the community components and not the pages.  Without any error - I don't know how to proceed.

Below is the doctor output:
[1694688126910-diagnosis.json.txt](https://github.com/forcedotcom/cli/files/12607843/1694688126910-diagnosis.json.txt)

**sfdx-project.json**:
```json
{
  "packageDirectories": [
    {
      "path": "force-app",
      "package": "MyPackageName",
      "versionName": "ver 0.1",
      "versionNumber": "0.1.0.NEXT",
      "default": true,
      "versionDescription": "Help"
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "58.0",
  "packageAliases": {
    "MyPackageName": "0Ho5j0000008AAAAAA",
    "MyPackageName@0.1.0-1": "04t5j000000AAAAAA",
    "MyPackageName@0.1.0-2": "04t5j000000AAAAAA",
    "MyPackageName@0.1.0-3": "04t5j000000AAAAAA",
    "MyPackageName@0.1.0-4": "04t5j000000AAAAAA",
    "MyPackageName@0.1.0-5": "04t5j000000AAAAAA",
    "MyPackageName@0.1.0-6": "04t5j000000AAAAAA",
    "MyPackageName@0.1.0-7": "04t5j000000AAAAAA",
    "MyPackageName@0.1.0-8": "04t5j000000AAAAAA",
    "MyPackageName@0.1.0-9": "04t5j000000AAAAAA",
    "MyPackageName@0.1.0-10": "04t5j00000AAAAAAE",
    "MyPackageName@0.1.0-11": "04t5j00000AAAAAAE"
  }
}
```

---
name: Bug report
about: Create a report to help us improve
title: '`sf package version create` fails without an error, log, or `Package2VersionCreateRequest` being created'
labels: 'investigating'
assignees: ''

---

> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

**Comment by mshanemc** [comment] 2023-09-14 17:07
There's definitely a bug with the spinner covering up the command's output (which would include the error), so I'm closing this as a duplicate of
https://github.com/forcedotcom/cli/issues/2434

Until we fix that, the best workaround is to add `--json` which will give you the error output. 

You could also try piping the stdout and stderr to files to get their output (where it doesn't overwrite the previous line)

**Closed as completed by mshanemc** 2023-09-14 17:07 UTC
