### ISSUE TITLE
SFDX Retrieve Source from Org not appearing to work correctly

### ISSUE THREAD

**Issue by JAyres-ArlanisReply** [forcedotcom/cli#1524] opened 2022-05-17 15:09 UTC
### Summary

We use Visual Studio Code's Salesforce CLI extension (via the Salesforce Extension Pack) to pull changes from our sandbox orgs and move them to our git repositories. Recently, several users have reported that the Retrieve Source from Org functionality is not working correctly. The loading bar is shown until the task times out. This has not occurred in the past and we are on the most recent version of both Visual Studio Code and Salesforce CLI. The issue only appears to occur on sandbox environments and does not occur when connected to a production org.

If the task is left to run until time-out, it eventually cites the error "Cannot read properties of undefined (reading 'type')".

Uninstalling and reinstalling the Salesforce Extension Pack does not resolve the issue. Switching to a production org resolves the issue, but changing back to a sandbox reintroduces it.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Install Visual Studio Code and the Salesforce Extension Pack.
1.  Successfully authorize a sandbox org following the usual procedure.
1.  Using the Org Browser, navigate to an item and attempt to retrieve its metadata (for example, a Custom Object).

### Expected result

The item should have downloaded to the local repository after the successful resolution of the SFDX: Retrieve Source from Org task.

### Actual result

The SFDX: Retrieve Source from Org function does not resolve and eventually (20 minutes+) times out with an error.

### System Information

{
        "cliVersion": "sfdx-cli/7.124.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.13.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.7 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.3 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.2 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.22 (core)",
                "apex 0.3.0 (core)",
                "auth 1.7.4 (core)",
                "config 1.2.41 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.3 (core)",
                "generator 1.2.1 (core)",
                "limits 1.2.2 (core)",
                "org 1.8.4 (core)",
                "salesforce-alm 53.1.1 (core)",
                "schema 1.0.10 (core)",
                "sfdx-cli 7.124.0 (core)",
                "source 1.2.5 (core)",
                "telemetry 1.2.8 (core)",
                "templates 52.4.0 (core)",
                "trust 1.0.11 (core)",
                "user 1.5.2 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
}

**Comment by iowillhoit** [comment] 2022-05-17 15:44
This is a known issue that is unrelated to the CLI. I am working on getting a public facing record of this performance degradation for folks to track. I am going to close this as a duplicate of https://github.com/forcedotcom/cli/issues/1522. Thanks @JAyres-ArlanisReply

**Closed as completed by iowillhoit** 2022-05-17 15:44 UTC
Labels: duplicate

**Comment by talk2bks** [comment] 2024-02-27 22:46
I use the .forceignore a lot to manage how I'm downloading and loading into orgs. This .forceignore will block files from being downloaded. Just found that out today.
