### ISSUE TITLE
Issue Validating with Scratch Orgs When Working with a Community and State and Country Picklists

### ISSUE THREAD

**Issue by Jkenney94** [forcedotcom/cli#553] opened 2020-08-07 19:12 UTC
### Summary

Using a Scratch Org for validation in Pipelines with a project involving a Community and Country and State Picklists, a standard Apex Class created for the Community (MyProfilePageController) has a failing unit test due to an invalid initialization of the User within the Scratch Org. User's Address is set to "US" and once Country and State Picklists are enabled the expectation is for this to be "United States" on the record. This seems to be a recent bug, I had a similar project setup roughly a year ago where all of this was working as expected.

### Steps To Reproduce:

**Repository to reproduce:** [sfdx-StateAndCountry-Community-Bug](https://github.com/Jkenney94/sfdx-StateAndCountry-Community-Bug)

Reproduction Steps:
1.  Create a new Scratch Org (the Scratch org config should enable Communities and State and Country Picklist Features) using `sfdx force:org:create -s -f ./config/project-scratch-def.json -a ScratchOrg`
1.  Push your sample Community to the scratch org using `sfdx force:source:push`
1.  Run Local Tests using `sfdx force:apex:test:run -l RunLocalTests -w 15`

Alternatively, use the setupScript.sh within the repo

### Expected result

All tests should be passing, this was working as expected in a past project done roughly a year ago.

### Actual result

MyProfilePageControllerTest.testSave fails because an Exception is thrown preventing the User Record from being updated thus preventing the System.assert to validate the record was updated.

The Exception is caused by calling Update on the Current User with a Country of "US" but enabling State and Country Picklists expects the Country to be from the picklist (in this case it should be "United States"). This causes a CI/CD process validating with Scratch Orgs to fail if verifying tests are working as expected.

The workaround is to run an Anonymous Apex Script to update the User's Country to be "United States" to then bypass the Exception, but I believe this should not be necessary.

### Additional information
User Record:
<img width="575" alt="User Record" src="https://user-images.githubusercontent.com/8562055/89680067-d7d69300-d8b7-11ea-892e-aca2b8804c6d.png">

Test Results:
<img width="820" alt="Test Results" src="https://user-images.githubusercontent.com/8562055/89680091-e329be80-d8b7-11ea-931f-0b38eeb33769.png">

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.69.0 darwin-x64 node-v12.18.2

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.2.0
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.5.0 (core)
├─ custom-metadata 1.0.8 (core)
├─ salesforcedx-templates 49.2.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 49.5.0 (core)
sfdx-cli 7.69.0 (core)

**OS and version**: MacOS Catalina 10.15.6

**Comment by shetzel** [comment] 2020-10-23 23:06
I've asked the apex team if this is working as designed or a bug.  You might want to post in a salesforce community as well.

**Comment by iowillhoit** [comment] 2023-10-20 20:14
Hey @Jkenney94, I am grooming some old Github Issues. Is this still an issue? I tried to replicate it using your repo but had to remove `enableSetPasswordInApi` from the scratch org definition file since it was [removed in Spring 21](https://help.salesforce.com/s/articleView?id=release-notes.rn_api_meta.htm&release=230&type=5#:~:text=REMOVED%3A%20The%20enableSetPasswordInApi,API%20version%2051.0.). After removing that setting, there were multiple test failures.

**Comment by iowillhoit** [comment] 2023-11-01 18:12
Going to close this issue for now. If this still a problem, please open a new Issue with updates to the reproduction steps. Thank you!

**Closed as completed by iowillhoit** 2023-11-01 18:12 UTC
Labels: owned by another team, area:apex

**Comment by joeythomaschaske** [comment] 2026-04-09 14:06
It's still an issue. We pulled down the class contents and the test is using `seeAllData=true` which definitely should not be coming from a class provided by salesforce

**Comment by jfeingold35** [comment] 2026-04-09 15:40
Can you open a new issue and add reproduction steps, please?

**Comment by herakles86** [comment] 2026-04-15 01:16
We have the same issue when trying to create an unlocked package.
