### ISSUE TITLE
FieldService settings fail to be retrieved by the CLI even though they are returned from the Metadata API.

### ISSUE THREAD

**Issue by bowdi** [forcedotcom/cli#964] opened 2021-04-09 14:28 UTC
### Summary

FieldService settings fail to be retrieved by the CLI even though they are returned from the Metadata API. You can see the Metadata API responding with the FieldService.settings file if you set the SFDX_MDAPI_TEMP_DIR env var but the matching source file is never created.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Create a scratch org using the above repo
1.  Set the SFDX_MDAPI_TEMP_DIR env var so the retrieve request and response are retained.
1.  Run the command `sfdx force:source:retrieve -m Settings:FieldService`
1.  You receive a 'No results found' error
1.  Look at the path you configured with the env var SFDX_MDAPI_TEMP_DIR and notice two folders, one with the request and one with the response with the FieldService.settings file included

### Expected result

A FieldService.settings-meta.xml file is created / updated. 

### Actual result

A 'No results found' found error is returned.

### Additional information

If you enable the vs code setting salesforcedx-vscode-core.experimental.deployRetrieve the error is not received if requested through the org browser.

**SFDX CLI Version**: sfdx-cli/7.92.0 win32-x64 node-v15.10.0

**SFDX plugin Version**

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-2 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.4.10 (core)
config 1.2.6 (core)
generator 1.1.5 (core)
salesforcedx 51.4.0 (core)
├─ limits 1.0.4 (core)
├─ schema 1.0.4 (core)
├─ apex 0.1.4 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 51.3.0 (core)
├─ org 1.3.3 (core)
├─ user 1.2.0 (core)
├─ custom-metadata 1.0.11 (core)
└─ salesforce-alm 51.4.0 (core)
sfdx-cli 7.92.0 (core)
sfdx-git-delta 4.2.0
telemetry 1.1.1 (core)

**OS and version**: Microsoft Windows 10 Enterprise - 10.0.18363 / Build 18363

**Comment by bowdi** [comment] 2021-04-09 14:35
Here is the log file:

[source-retrieve.log](https://github.com/forcedotcom/cli/files/6286471/source-retrieve.log)

Retrieved using:
```powershell
sfdx force:source:retrieve -m Settings:FieldService --dev-debug --json *> source-retrieve.log
```

**Comment by mshanemc** [comment] 2023-04-05 23:00
works for me, probably ok since the new source plugin shipped.  I'm closing, if you can still reproduce this please open a new issue.

<img width="1469" alt="Screenshot 2023-04-05 at 5 59 12 PM" src="https://user-images.githubusercontent.com/4261788/230230307-99c35275-392e-4d8f-9d1b-9b80b859ae17.png">

**Closed as completed by mshanemc** 2023-04-05 23:00 UTC
