### ISSUE TITLE
INVALID_SESSION_ID when deploying with force:source:deploy

### ISSUE THREAD

**Issue by Bartheleway** [forcedotcom/cli#912] opened 2021-03-11 08:49 UTC
### Summary

After the OAuth token of my session expire, it seems that sfdx doesn't refresh it automatically anymore.

### Steps To Reproduce:

1. Authorize an org (sandbox) on your VS Code sfdx project
2. Wait or make your OAuth token to expire
3. Try to use "force:source:deploy" on any file, you should get the error

### Expected result

Refresh the token and deploy the source

### Actual result

Receiving: INVALID_SESSION_ID: Session expired or invalid

### Additional information

SFDX version : 7.90.2

Using the "open org" command seems to refresh the token. We have to do it every time that token expire, annoying.
This is probably related to issue #899

**Comment by MuriloKakazu** [comment] 2021-03-16 16:26
This seems to be caused by the recent changes in which the CLI started using Salesforce's REST API to deploy by default ([since v7.90.2](https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md#5122-march-4-2021---cli-7902)). If you force it to deploy using SOAP API, it will refresh your expired access token:

```bash
$ SFDX_REST_DEPLOY=false sfdx force:source:deploy <...>
```

After refreshing your access token that way, or by `sfdx force:org:open` as you said, you can then go back to deploying with REST until the token expires again...

![image](https://user-images.githubusercontent.com/15305591/111343379-215f3b80-865a-11eb-8a0e-b27cebb10960.png)

It seems that `sfdx force:org:list` still displays the orgs as `Connected` because it conveniently refreshes the access tokens for non-scratch orgs [ref](https://github.com/salesforcecli/plugin-org/blob/ea42676ab24e086155088d41d5ef1f7aeb98c17b/src/shared/orgListUtil.ts#L295)

**Comment by shetzel** [comment] 2021-03-16 22:47
This is a duplicate of #899 
Closing this in favor of the first report.  It's a bug and will be fixed asap.

**Closed as completed by shetzel** 2021-03-16 22:47 UTC
Labels: investigating
