### ISSUE TITLE
Auto corrected command for version fails

### ISSUE THREAD

**Issue by andyjb** [forcedotcom/cli#1412] opened 2022-02-16 23:43 UTC
### Summary

When accepting the SFDX-suggested `version` command if initially entered incorrectly, it still reports it as an invalid entry

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Run the following command: `sfdx --verison`
1.  SFDX will spot the typo and suggest `version` as the intended input. Select y

### Expected result

The output should be as though `sfdx --version` was initially executed

### Actual result

Error message: ` ›   Warning: version is not a sfdx command.`

### System Information

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
{
        "cliVersion": "sfdx-cli/7.137.1",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.13.2",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/lwc-dev-mobile 1.4.0",
                "@salesforce/lwc-dev-server 2.11.0",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.1 (core)",
                "apex 0.8.0 (core)",
                "auth 1.8.1 (core)",
                "config 1.3.19 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.2 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.1 (core)",
                "salesforce-alm 53.9.0 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.137.1 (core)",
                "sfdx-hardis 2.68.2",
                "source 1.8.11 (core)",
                "telemetry 1.4.0 (core)",
                "templates 53.5.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Darwin 21.2.0"
}
### Additional information

<img width="440" alt="Screenshot 2022-02-16 at 23 43 04" src="https://user-images.githubusercontent.com/1558461/154376250-4c36a3cd-08b1-48a8-8dc8-2212bd4f0029.png">

**Comment by mshanemc** [comment] 2022-02-17 14:37
duplicate of https://github.com/forcedotcom/cli/issues/1268

**Closed as completed** 2022-02-17 14:37 UTC
Labels: investigating
