### ISSUE TITLE
ManagedContentType not supported through metadata api

### ISSUE THREAD

**Issue by KetanAdkar** [forcedotcom/cli#452] opened 2020-06-23 14:56 UTC
### Summary

getting an error - ERROR running force:source:retrieve:  We can’t retrieve the specified metadata object: ManagedContentType. Certain metadata types, like ManagedContentType are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**:

**Comment by FabienTaillon** [comment] 2020-07-27 09:28
This is a duplicate of #418 
ManagedContentTypes can be retrieved by the Metadata API, but not in source format.
So you can't use `sfdx force:source:retrieve`, but `sfdx force:mdapi:retrieve` will work.

You won't be able to use it directly in a sfdx project though as source format isn't working for this metadata type, but you can still deploy it separately with `sfdx force:mdapi:deploy`.

**Closed as completed** 2020-07-27 17:27 UTC
Labels: duplicate

**Comment by kamran-jabbar** [comment] 2020-08-11 20:14
@FabienTaillon As I am trying to get full sandbox copy on my local machine so will that command `sfdx force:mdapi:retrieve `what I have inside pacakge.xml from sandbox? How can I make sure it copies everything?

**Comment by FabienTaillon** [comment] 2020-08-12 06:28
Yes it will work. At least it will give you everything that is available in the Metadata API for this Metadata Type.
