### ISSUE TITLE
sf project deploy quick command issue

### ISSUE THREAD

**Issue by shabu74** [forcedotcom/cli#2171] opened 2023-05-30 00:13 UTC
### Summary

When I use a deployment job id of a validated deployment in sf project deploy quick, deployment will be successfully completed in Salesforce. But this command is getting failed error.

### Steps To Reproduce:

sf project deploy start --async --dry-run --ignore-conflicts --manifest releasePackage/package.xml --post-destructive-changes releasePackage/destructiveChangesPost.xml --target-org $targetusername --test-level RunSpecifiedTests --tests sampletestclaas --json --api-version $SF_API_VERSION > deploy-result.json
deploy_id=$(jq -r '.result.id' deploy-result.json)
sf project deploy quick --async --job-id $deploy_id --json > deploy-result.json

### Expected result

Deployment triggered successfully and I should get deploy-result.json with details details of deployment including status.

### Actual result
Deployment triggered and completed  successfully. But I got deploy-result.json with erro details 
{
"code": 1,
"context": "DeployMetadataQuick",
"commandName": "DeployMetadataQuick",
"message": "undefinedComponentSet",
"name": "SfError",
"status": 1,
"stack": "SfError: undefinedComponentSet
at ComponentSetBuilder.build (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSetBuilder.js:140:19)
at buildComponentSet (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-deploy-retrieve/lib/utils/deploy.js:47:57)
at async DeployMetadataQuick.run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-deploy-retrieve/lib/commands/project/deploy/quick.js:30:30)
at async DeployMetadataQuick._run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:117:22)
at async Config.runCommand (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:329:25)
at async run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:89:16)",
"exitCode": 1,
"warnings": [
"org-api-version configuration overridden at 57.0"
]
}

### System Information

bash
{
  "cliVersion": "@salesforce/cli/1.79.5",
  "architecture": "linux-x64",
  "nodeVersion": "node-v20.2.0",
  "osVersion": "Linux 5.15.0-1035-aws",
  "shell": "bash",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.2.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 3.0.1 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.15 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.20 (core)",
    "@salesforce/cli 1.79.5 (core)",
    "apex 2.2.19 (core)",
    "auth 2.7.15 (core)",
    "data 2.3.18 (core)",
    "deploy-retrieve 1.9.1 (core)",
    "info 2.6.13 (core)",
    "limits 2.3.15 (core)",
    "login 1.2.9 (core)",
    "org 2.9.0 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.8 (core)",
    "sobject 0.1.19 (core)",
    "source 2.10.9 (core)",
    "telemetry 2.2.0 (core)",
    "templates [55](https:///-/jobs/6962880#L55).4.15 (core)",
    "trust 2.4.18 (core)",
    "user 2.3.13 (core)"
  ]
}

### Additional information

_Feel free to attach a screenshot_.

**Comment by iowillhoit** [comment] 2023-05-31 15:37
Hey @shabu74, this looks like a duplicate of https://github.com/forcedotcom/cli/issues/2098. We have a work item to track this.

FYI: I would encourage you to use the `sf project deploy validate` command to prepare a deployment for a `quick` deploy later.

**Closed as not planned** 2023-06-02 15:03 UTC
Labels: investigating

**Comment by shabu74** [comment] 2023-06-02 23:19
But project deploy validate command does not have the argumentcto specify post destructive package xml. Right? So, how can we validate a destructive deployment?
