### ISSUE TITLE
No longer can authenticate an org in Fedora 33

### ISSUE THREAD

**Issue by docbill** [forcedotcom/cli#839] opened 2021-02-09 14:57 UTC
### Summary

As of Monday February 8th, 2021, authorizing an org is no longer working.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Run a command like:  sfdx force:auth:web:login --setalias merge --instanceurl https://redhat--merge.my.salesforce.com --setdefaultusername
2. Login on the host.
3. Authorise
4. Wait

### Expected result

The host should successfully authorize.  The browser window should either continue to the host login to the host, or should autoclose.

### Actual result

The connection to localhost:1717 freezes.  After 5 minutes or so it will eventually error out in the browser with a now response error.   If you strace the running process you'll see it is waiting forever on a read.

### Additional information

_Feel free to attach a screenshot_.

sfdx-cli/7.85.1-2fb9e41053 linux-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
sfdx-cli/7.85.1-2fb9e41053 linux-x64 node-v12.18.3
[briemers@briemers integration-enhancements]$ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.10.0
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
etcopydata 0.5.7
generator 1.1.3 (core)
mo-dx-plugin 0.3.2
salesforcedx 50.15.0 (core)
├─ limits 1.0.3 (core)
├─ user 1.0.9 (core)
├─ schema 1.0.3 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ templates 50.4.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 50.15.0 (core)
sfdx-cli 7.85.1 (core)

**OS and version**:

Fedora 33 x64

Additional notes:

I have found a workaround, accidentally when attempting to debug.  If I run the following command it works:

strace -f -o strace.txt sfdx force:auth:web:login --setalias merge --instanceurl https://redhat--merge.my.salesforce.com --setdefaultusername

Now to me this indicates the bug is happening in the way processes are forked and detached.   The observer always effects the observerd.  As soon as I run the strace following the forks, it forces all the forks to stay attached together.   

I am guessing this is probably a defect due to a fedora update, not an update to sfdx's node.js version.   But I have absolutely no idea what component to report the defect against, or what information would be useful in such a defect report.   It is equally likely a defect was fixed in fedora, which sfdx was accidentally relying on.

**Comment by docbill** [comment] 2021-02-09 15:08
A second defect that has existing for quite sometime and is probably directly related, is in Linux when running the command:

sfdx force:mdapi:deploy -d "$mdapipath" --testlevel=RunSpecifiedTests -r $TESTCLASSES --loglevel=warn -w 30

The command will return and a prompt will appear on the screen, but console output will continue to the console, indicating the child process is still running.   

The reason I say this is probably related, is it is another example where the child process is being detached from the parent, when it shouldn't be.   This happens when using the wrong type of fork.   Again putting an strace on the whole execution works around the problem.

**Comment by mshanemc** [comment] 2021-02-09 15:29
@docbill thanks for helping with the detective work.  Most of what's happening for `auth:web:login` is open-sourced, so you may want to compare your trace/debug to the following files in 2 repos:

plugin-auth (where that command lives)
https://github.com/salesforcecli/plugin-auth/blob/main/src/commands/auth/web/login.ts

sfdx-core (where the local web server for handling the oauth callback runs)
https://github.com/forcedotcom/sfdx-core/blob/139cb00cf95378fc0a3af58b3af3b255f5a78394/src/webOAuthServer.ts

To narrow the problem, can you tell if the auth happened successfully on the org from the ui/loginHistory?  That way we can know if it's an auth error OR the local webserver not getting the success message.

**Comment by docbill** [comment] 2021-02-09 16:09
The authorization on the org succeeds.  Each time I issue the command there is a new token listed.  And if I am patient enough to what for the webbrowser to timeout I can see the actual token in the localhost URL as a  get argument.  (e.g. following the ? in the url).

My best guess is the child process listening on 1717 is attempting to talk to another process which is no longer listening on the pipe.   But that is just a guess.  It has been several decades since I've debugged any C code, so I'm not even sure the correct package to install to get the debugging symbols or how to step through the code to do so.   About the only way I would find and correct the bug, is I just happen to recognize the exact same mistake I've made sometime in the distant past.

**Comment by mshanemc** [comment] 2021-02-09 16:30
on the cli command, you can run with `--dev-debug` to get a ton of log output.  

Knowing that auth succeeded and there's a callback problem is helpful for us.

**Comment by docbill** [comment] 2021-02-09 17:06
Here are some output files that may help.  The briemers.* files are the ones from running without an strace, the briemers2.* files are from running with an strace.

[briemers.log](https://github.com/forcedotcom/cli/files/5952932/briemers.log)
[briemers.txt](https://github.com/forcedotcom/cli/files/5952933/briemers.txt)
[briemers2.log](https://github.com/forcedotcom/cli/files/5952934/briemers2.log)
[briemers2.txt](https://github.com/forcedotcom/cli/files/5952935/briemers2.txt)
[briemers2.strace.bz2.zip](https://github.com/forcedotcom/cli/files/5952953/briemers2.strace.bz2.zip)

Note: I had to double compress the strace file to fit under the 10MB file size limit.

**Comment by dvon88** [comment] 2021-02-10 09:05
Duplicate of #834

**Comment by the1mattkaufman** [comment] 2021-02-11 06:27
@docbill Your workaround using strace worked for me too.  I'm on Debian not Fedora

**Comment by docbill** [comment] 2021-02-12 00:34
Yeah.  I tried replacing /usr/local/bin/sfdx with a script to always call strace, just because the same bug is hitting many different sfdx commands.  However, it turns out that breaks the scenario when sfdx legitimately tries to leave a daemon running in the background.   So it is a good command line solution, but it is not good for fixing issues like running a test class never returns anymore if there is a test failure.

**Comment by mdonnalley** [comment] 2021-02-16 22:28
Duplicate of https://github.com/forcedotcom/cli/issues/783

**Closed as completed by mdonnalley** 2021-02-16 22:28 UTC
Labels: duplicate, tracked elsewhere
