### ISSUE TITLE
"ManagedContentType" are not currently supported by the CLI

### ISSUE THREAD

**Issue by dpahadiya-salesforce** [forcedotcom/cli#355] opened 2020-03-27 14:53 UTC
Fetching all the metadata from VS Code and getting below error.

ERROR running force:source:retrieve:  We can’t retrieve the specified metadata object: ManagedContentType. Certain metadata types, like ManagedContentType are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type

**Comment by clairebianchi** [comment] 2020-03-31 18:04
@dpahadiya-salesforce Thank you. I will file a bug on the team that owns that metadata and get it fixed.

**Comment by clairebianchi** [comment] 2020-03-31 18:07
@dpahadiya-salesforce what version of the CLI are you on?

**Comment by ahewardUF** [comment] 2020-04-09 20:57
> @dpahadiya-salesforce what version of the CLI are you on?

@clairebianchi I've confirmed this error on CLI ver7.50.0 and 7.53.0. 

"ERROR running force:source:retrieve:  We can’t retrieve the specified metadata object: ManagedContentType. Certain metadata types, like ManagedContentType are not currently supported by the CLI"

**Comment by RupertBarrow** [comment] 2020-04-14 14:21
Duplicate with #151

**Comment by jsmithdev** [comment] 2020-05-08 15:50
Just fyi, hit as well today using vs code org browser: metadata

`sfdx -v`
`sfdx-cli/7.53.0 linux-x64 node-v10.15.1`

> ERROR running force:source:retrieve:  We can’t retrieve the specified metadata object: ManagedContentType. Certain metadata types, like ManagedContentType are not currently supported by the CLI.
> File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
> 11:44:56.420 sfdx force:source:retrieve -m ManagedContentType
>  ended with exit code 1

**Comment by gwynnebaer** [comment] 2020-06-16 15:53
FYI, this also applies to `sfdx force:mdapi:convert` commands for the same reasons, although the error is less useful: 
`ERROR running force:mdapi:convert:  An error was encountered processing path: metadata/unpackaged/managedContentTypes/news.managedContentType`

**Comment by AltiusRupert** [comment] 2020-07-26 11:19
@clairebianchi This is a duplucate of #151 which is closed, so could possibly also be closed.

**Comment by FabienTaillon** [comment] 2020-07-27 09:26
Isn't this one a duplicate of #418 too ?

**Closed as completed** 2020-07-27 17:27 UTC
Labels: bug, duplicate
